import {createServer} from 'node:http';
import {createWriteStream} from 'node:fs';
import {mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
const token=randomBytes(24).toString('hex');
await mkdir('artifacts/tabby-live-video',{recursive:true});
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Tabby window recorder</title><style>body{font:20px/1.6 system-ui;background:#f6f5f0;color:#272923;max-width:800px;margin:80px auto}button{font:inherit;background:#ff7745;border:0;padding:16px 25px;border-radius:10px;margin-right:15px}p{color:#77796f}</style><h1>Tabby window recorder</h1><p>Choose only the Chrome for Testing window showing the React documentation. No microphone or system audio is recorded. Footage is saved locally in the project.</p><button id="start">Record Chrome window</button><button id="stop" disabled>Stop and save recording</button><p id="status">Ready</p><script>
let recorder,stream,chunks=[],start;
document.querySelector('#start').onclick=async()=>{try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:30},displaySurface:'window'},audio:false});const track=stream.getVideoTracks()[0];if(track.getSettings().displaySurface!=='window'){track.stop();document.querySelector('#status').textContent='Select Window, then the Chrome for Testing demo window.';return;}chunks=[];start=Date.now();recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:12000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'video/webm'});document.querySelector('#status').textContent='Saving recording…';const r=await fetch('/save?token=${token}',{method:'POST',body:blob});document.querySelector('#status').textContent=await r.text();document.querySelector('#start').disabled=false;document.querySelector('#stop').disabled=true;};track.onended=()=>{if(recorder.state!=='inactive')recorder.stop()};recorder.start(500);document.querySelector('#start').disabled=true;document.querySelector('#stop').disabled=false;document.querySelector('#status').textContent='Recording: '+track.label;}catch(e){document.querySelector('#status').textContent=e.name+': '+e.message}};
document.querySelector('#stop').onclick=()=>recorder.stop();
</script></html>`;
const server=createServer((req,res)=>{if(req.method==='GET'&&req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(req.method==='POST'&&req.url==='/save?token='+token){const file='artifacts/tabby-live-video/browser-'+Date.now()+'.webm',out=createWriteStream(file);let size=0;req.on('data',d=>{size+=d.length;if(size>500*1024*1024){out.destroy();req.destroy();}});req.pipe(out);out.on('finish',()=>{console.log('Saved '+file+' '+size+' bytes');res.end('Saved '+file);});out.on('error',()=>res.writeHead(500).end('Save failed'));return;}res.writeHead(404).end();});
server.listen(4340,'127.0.0.1',()=>console.log('Local window recorder: http://127.0.0.1:4340'));
