import { useEffect, useState } from 'react';
import { Check, ExternalLink, FileText, MessageCircle, RotateCcw, Send } from 'lucide-react';
import type { AppState } from '../shared/types';
import { AMBIGUOUS_ORIGIN } from '../shared/ambiguous';
import { isExtension } from './bridge';
import { errorText } from './errors';
type Act = (type: string, payload?: Record<string, unknown>) => Promise<any>;
export function AmbiguousView({ state, act, busy }: { state: AppState; act: Act; busy: boolean }) {
  const a = state.ambiguous; const [content, setContent] = useState(a.report?.content || ''); const [copied, setCopied] = useState(false);
  useEffect(() => { if (isExtension && state.settings.pairToken) void act('AMBIGUOUS_STATUS'); }, []);
  useEffect(() => { if (!a.status.pending) return; const timer = setInterval(() => { if (!busy) void act('AMBIGUOUS_STATUS'); }, 5000); return () => clearInterval(timer); }, [a.status.pending, busy]);
  useEffect(() => { setContent(a.report?.content || ''); setCopied(false); document.querySelector('.ambiguous-report')?.scrollIntoView({ block: 'start' }); }, [a.report?.id, a.report?.createdAt]);
  const sessions = [state.session, ...state.history].filter(s => s?.phase === 'finished' && s.ambiguous);
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span />AMBIGUOUS · TEAM CHAT</div><h1>Bring the task. Share the progress.</h1><p>A message becomes your next focus task. Send the result back when you’re ready.</p></div></div>
    <section className="card project-section ambiguous-connection"><div className="card-top"><h2><MessageCircle size={20} /> Your team, connected</h2><span className="pill">{a.status.transport.toUpperCase()}</span></div><p>Connect your Ambiguous account, choose a channel and review a message before saving it as a task. Reports go to the original thread only after you review and send them.</p>
      {!isExtension && <p className="muted">Install Tabby to connect your team chat.</p>}
      {!state.settings.pairToken && <p className="muted">Start Tabby’s local server and add its connection token in Settings first.</p>}
      <div className="button-row"><button className="btn primary" disabled={busy || !isExtension || !state.settings.pairToken || a.status.pending} onClick={() => act('AMBIGUOUS_CONNECT')}>{a.status.pending ? 'Waiting for sign-in…' : a.enabled && a.status.configured ? 'Check connection' : 'Connect Ambiguous'}</button>{a.enabled && a.status.configured && <button className="btn secondary" disabled={busy} onClick={() => act('AMBIGUOUS_CHANNELS')}><RotateCcw size={15} />Load channels</button>}{a.enabled && <button className="text-button" disabled={busy} onClick={() => act('AMBIGUOUS_DISCONNECT')}>{a.status.pending ? 'Cancel sign-in' : 'Disconnect'}</button>}</div>
      {a.status.pending && <p role="status">Finish sign-in in the Ambiguous tab, then return here.</p>}
      {a.status.error && <p role="alert">{errorText(a.status.error)}</p>}
      {a.error && <p role="alert">{errorText(a.error)}</p>}
      <p className="small-label">Messages stay local until you save a task. Chat browsing and factual session reports do not call your AI provider.</p>
    </section>
    {a.enabled && a.status.configured && <section className="card project-section"><div className="card-top"><h2>Choose a team message</h2>{a.channelId && <button className="text-button" disabled={busy} onClick={() => act('AMBIGUOUS_MESSAGES', { channelId: a.channelId })}>Refresh messages</button>}</div><label>Ambiguous channel<select value={a.channelId} disabled={busy || !a.channels.length} onChange={e => { if (e.target.value) void act('AMBIGUOUS_MESSAGES', { channelId: e.target.value }); }}><option value="">{a.channels.length ? 'Choose a channel' : 'Load your channels first'}</option>{a.channels.map(c => <option key={c.id} value={c.id}>{c.type === 'dm' ? '' : '#'}{c.name}{c.type === 'private' ? ' · Private' : ''}</option>)}</select></label>
      {a.messages.map(m => { const imported = state.tasks.some(t => t.ambiguous?.channelId === m.channelId && t.ambiguous.messageId === m.id); return <article className="ambiguous-message" key={m.id}><div className="card-top"><strong>{m.author}</strong><small>{m.createdAt ? new Date(m.createdAt).toLocaleString() : ''}</small></div><p className="preserve-lines">{m.content}</p><button className="text-button" disabled={busy || imported} onClick={() => act('AMBIGUOUS_DRAFT', { messageId: m.id })}>{imported ? <Check size={15} /> : <FileText size={15} />}{imported ? 'Added to Tabby' : 'Review task'}</button></article>; })}
      {a.channelsTruncated && <p className="muted">Ambiguous returned a partial channel list. Up to 500 channels are shown.</p>}
      {a.channelId && !a.messages.length && <p>No messages in this page.</p>}{a.hasMore && a.nextCursor && <button className="btn secondary" disabled={busy} onClick={() => act('AMBIGUOUS_MESSAGES', { channelId: a.channelId, cursor: a.nextCursor })}>Older messages</button>}
    </section>}
    {a.report && <section className="card project-section ambiguous-report"><div className="eyebrow">REVIEW BEFORE SENDING</div><h2>Reply to #{a.report.source.channelName}</h2><p>This report will be posted in the original task’s thread.</p><label>Session report<textarea rows={12} maxLength={6000} value={content} disabled={a.report.state !== 'draft'} onChange={e => setContent(e.target.value)} /></label>{a.report.state === 'draft' && <div className="button-row"><button className="btn primary" disabled={busy || !content.trim()} onClick={() => act('AMBIGUOUS_SEND_REPORT', { reportId: a.report!.id, content, confirm: true })}><Send size={15} />Send report to Ambiguous</button><button className="btn secondary" disabled={busy} onClick={() => act('AMBIGUOUS_CANCEL_REPORT')}>Cancel</button></div>}{a.report.state === 'sending' && <p role="status">Sending your report…</p>}{a.report.state === 'sent' && <p role="status" className="success-text">Report sent to the original thread.</p>}{a.report.state === 'unknown' && <><p role="alert">Delivery could not be confirmed. Check the original thread before sharing again. Tabby will not resend automatically.</p><button className="btn secondary" onClick={async () => { try { await navigator.clipboard.writeText(content); setCopied(true); } catch { setCopied(false); } }}>{copied ? 'Copied' : 'Copy report'}</button></>}<a className="text-button" href={AMBIGUOUS_ORIGIN} target="_blank" rel="noreferrer">Open Ambiguous <ExternalLink size={14} /></a></section>}
    <section className="card project-section"><h2>Completed focus sessions</h2>{!sessions.length && <p>Save a task from Ambiguous, focus on it, then finish the session. Your report will be ready to review here.</p>}{sessions.map(s => s && <article className="ambiguous-message" key={s.id}><h3>{s.goal}</h3><p className="muted">#{s.ambiguous!.channelName} · {new Date(s.startedAt).toLocaleDateString()}</p>{s.ambiguousReport ? <p>{s.ambiguousReport.state === 'sent' ? 'Report shared' : 'Check the original thread: delivery is unconfirmed.'}</p> : <button className="text-button" disabled={busy || !a.enabled} onClick={() => act('AMBIGUOUS_PREPARE_REPORT', { sessionId: s.id })}>Review session report</button>}</article>)}</section>
  </>;
}
