const errors: Record<string, string> = {
  INVALID_MISSION_GOAL: 'Describe your goal in 5–1,000 characters and choose 5–180 minutes.',
  INVALID_MISSION_PLAN: 'The plan could not be validated. Try planning your mission again.',
  MISSION_TIME_BUDGET: 'This plan exceeds your time budget. Try a smaller goal or more time.',
  MISSION_BUSY: 'Tabby is already working on this mission. Wait or cancel the request.',
  MISSION_ALREADY_RUNNING: 'Stop or complete your current mission before starting another.',
  MISSION_PLAN_EXPIRED: 'This plan expired. Prepare a fresh plan before starting.',
  MISSION_NOT_ACTIVE: 'Start or continue a mission first.',
  MISSION_STEP_CHANGED: 'The current step changed. Review it before confirming.',
  MISSION_FINISHED: 'Every step is already complete. Start a new mission.',
  INVALID_AI_TAB: 'AI selected a tab outside the shared context. Prepare a fresh plan.',
  AMBIGUOUS_NOT_CONFIGURED: 'Restart the local Tabby server with the updated code to connect Ambiguous.',
  AMBIGUOUS_AUTH_REQUIRED: 'Sign in to Ambiguous again, or check the server API key and channel permissions.',
  AMBIGUOUS_ACCESS_DENIED: 'Ambiguous did not grant access to this channel or action. Check your workspace permissions.',
  AMBIGUOUS_AUTH_FAILED: 'Ambiguous sign-in could not finish. Try Connect Ambiguous again.',
  AMBIGUOUS_AUTH_DENIED: 'Ambiguous sign-in was declined. Nothing was imported or sent.',
  AMBIGUOUS_AUTH_EXPIRED: 'The sign-in window expired. Connect Ambiguous again.',
  AMBIGUOUS_DISABLED: 'Connect Ambiguous before loading messages or sharing reports.',
  AMBIGUOUS_LOADING: 'A chat request is in progress. Wait for it to finish.',
  AMBIGUOUS_UNAVAILABLE: 'Ambiguous is unavailable. Your saved Tabby tasks are still here.',
  AMBIGUOUS_INVALID_RESPONSE: 'Ambiguous returned an unsupported response. No data was imported.',
  AMBIGUOUS_TOOL_UNAVAILABLE: 'The required Ambiguous MCP tool is unavailable. Check the connection or configure the documented REST transport.',
  AMBIGUOUS_TOOL_FAILED: 'Ambiguous could not complete this operation. Check channel access.',
  AMBIGUOUS_RATE_LIMIT: 'Ambiguous rate limit reached. Wait before trying again.',
  AMBIGUOUS_CHANNEL_REQUIRED: 'Load your channels and choose one first.',
  AMBIGUOUS_MESSAGES_STALE: 'Refresh this channel before making a task from its messages.',
  AMBIGUOUS_ALREADY_IMPORTED: 'This message already has a Tabby task.',
  AMBIGUOUS_SESSION_REQUIRED: 'Finish a focus session linked to an Ambiguous task first.',
  AMBIGUOUS_REPORT_EXPIRED: 'This report preview expired. Cancel it and review a fresh report.',
  AMBIGUOUS_ALREADY_SENT: 'This session report has already been shared.',
  AMBIGUOUS_SENDING: 'The session report is being sent.',
  AMBIGUOUS_DELIVERY_UNKNOWN: 'Delivery could not be confirmed. Check the original Ambiguous thread. Tabby will not resend automatically.',
  AMBIGUOUS_REPORT_CHANGED: 'This report has an earlier delivery attempt. Check the original thread before sharing again.',
  AMBIGUOUS_RECEIPT_ERROR: 'The local delivery record could not be read. Sending is paused to prevent duplicates.',
  AMBIGUOUS_RECEIPT_LIMIT: 'The local delivery history is full. No message was sent.',
  ITEM_CHANGED: 'This item changed elsewhere. Your draft has been kept. Reopen the editor to review the current version before saving.',
  GOOGLE_NOT_CONFIGURED: 'Finish the one-time Google setup in Calendar & mail, then restart the local server.',
  GOOGLE_STORAGE_ERROR: 'Google credentials could not be read or saved on this computer. Check the local server setup.',
  GOOGLE_ACCESS_DENIED: 'Google access was declined. You can try connecting again.',
  GOOGLE_AUTH_FAILED: 'Google could not complete sign-in. Check your Desktop OAuth client and try again.',
  GOOGLE_AUTH_EXPIRED: 'Google sign-in expired. Start a new connection.',
  GOOGLE_SCOPE_REQUIRED: 'Google access is missing or the API is disabled. Enable the API in Google Cloud and reconnect.',
  GOOGLE_RECONNECT: 'Google access expired or was revoked. Connect this Google app again.',
  GOOGLE_UNREACHABLE: 'Google is unreachable. Check your connection and try again.',
  GOOGLE_UNAVAILABLE: 'Google is temporarily unavailable. Try again shortly.',
  GOOGLE_RATE_LIMIT: 'Google request limit reached. Wait a little before refreshing.',
  GOOGLE_INVALID_RESPONSE: 'Google returned an unexpected response. Refresh again.',
  CALENDAR_STALE: 'Refresh Calendar before sharing it with AI, or turn off Include calendar.',
  CHAT_IN_PROGRESS: 'A response is already in progress.',
  SYNC_IN_PROGRESS: 'This Google app is already refreshing.',
  REQUEST_CANCELLED: 'The response was stopped. You can try again.',
  INVALID_AI_TASK: 'AI referenced a task outside the shared context. No changes were applied.',
  PROPOSAL_EXPIRED: 'This proposal expired. Ask Tabby for a fresh suggestion.',
  TASK_CHANGED: 'This task changed since the suggestion. Ask Tabby to review it again.',
  INVALID_TASK: 'Enter a title up to 180 characters, up to 8 steps and a valid due date.',
  INVALID_PROJECT: 'Enter a project name up to 100 characters and a description up to 2,000 characters.',
  INVALID_NOTE: 'Enter a note title and keep the note under 4,000 characters.',
  PROJECT_UNAVAILABLE: 'Select an available project. Restore archived projects to add new items.',
  TASK_NOT_FOUND: 'This task is no longer available. Refresh and try again.',
  TASK_LIMIT: 'The workspace supports up to 500 tasks. Your existing tasks were kept.',
  PROJECT_LIMIT: 'The workspace supports up to 100 projects.',
  NOTE_LIMIT: 'The workspace note limit has been reached. Existing notes were kept.',
  PIN_LIMIT: 'The saved tab limit has been reached. Existing tabs were kept.',
  MCP_TOKEN_REQUIRED: 'Enter the separate MCP token from .local/mcp-token.txt.',
  SYNC_UNAVAILABLE: 'Chrome sync is unavailable. Your local data is safe. Try Sync now later.',
  SYNC_QUOTA_EXCEEDED: 'Chrome sync capacity or write limit reached. Your local data is safe. Reduce large notes or try again later.',
  SYNC_ITEM_TOO_LARGE: 'An item is too large for Chrome sync. Shorten it and try again. Your local data is safe.',
  SYNC_INVALID_LOCAL_DATA: 'Some local items need review before they can sync. Your data was kept.',
  SYNC_INVALID_REMOTE_DATA: 'The synced copy contains unsupported data. Your local data was kept.',
  AI_NOT_CONNECTED: 'Enable the included AI to get started.',
  CLOUD_OFFLINE: 'Tabby Cloud could not be reached. Check your internet connection and try again.',
  CLOUD_UNAVAILABLE: 'The included AI is temporarily unavailable. Please try again shortly.',
  CLOUD_RATE_LIMIT: 'You’re moving quickly! Wait a minute, then try AI again.',
  PAIRING_REQUIRED: 'Enter the connection token from .local/pairing.txt in Settings.',
  SERVER_OFFLINE: 'Local server is unavailable. Run npm run server.',
  API_KEY_INVALID: 'GPT Tunnel rejected the key. Check GPTUNNEL_API_KEY in .env.',
  ASTRA_NOT_FOUND: 'The catalog has no unique GPT-6 Astra. Choose an available model and explicitly set its ID in .env.',
  MODEL_UNAVAILABLE: 'The configured model is absent from your catalog. Choose an exact ID in .env.',
  MODEL_DEPRECATED: 'This model is retired. Choose a replacement in .env; no automatic substitution.',
  MODEL_SUBSTITUTED: 'The provider substituted a different model. The response was rejected. Choose a replacement in .env.',
  MODEL_FORBIDDEN: 'Your key has no access to this model.',
  API_BALANCE: 'Your GPT Tunnel balance is insufficient.',
  API_TIMEOUT: 'The model timed out. Please try again.',
  API_RATE_LIMIT: 'GPT Tunnel rate limit. Wait a minute.',
  LOCAL_RATE_LIMIT: 'Local request limit. Wait a minute.',
  INVALID_AI_JSON: 'Invalid AI response. No actions were applied.',
  INVALID_AI_SCHEMA: 'The AI response failed schema validation.',
  CONSENT_REQUIRED: 'Choose Enable AI in Focus, AI chat or Settings to allow AI assistance.',
  EXTENSION_REQUIRED: 'This feature requires the installed Chrome extension.',
  PAGE_UNAVAILABLE: 'This page is unavailable or excluded in Settings.',
  PERMISSION_DENIED: 'Site access was not granted. You can continue without reading page text.',
  WORK_TAB_CLOSED: 'The work tab is closed or has changed. Select a resource in Tabs.',
  TABS_CHANGED: 'Your tabs have changed. Prepare a fresh plan or grouping proposal.',
  STALE_RESPONSE: 'The context changed. Request a new suggestion.',
  SESSION_ALREADY_RUNNING: 'Finish the current session first.',
  INVALID_SESSION: 'Enter a goal and a duration between 1 and 480 minutes.',
  NO_SESSION: 'Start a focus session first.',
};
export function errorText(code: string) { return errors[code] || `Action failed (${code}). Please try again.`; }
