const errors: Record<string, [string, string]> = {
  AI_NOT_CONNECTED: ['AI не подключён. Добавьте ключ в локальный .env и перезапустите сервер.', 'AI is not connected. Add your key to the local .env and restart the server.'],
  PAIRING_REQUIRED: ['Укажите токен подключения из .local/pairing.txt в настройках.', 'Enter the connection token from .local/pairing.txt in Settings.'],
  SERVER_OFFLINE: ['Локальный сервер недоступен. Запустите npm run server.', 'Local server is unavailable. Run npm run server.'],
  API_KEY_INVALID: ['GPT Tunnel отклонил ключ. Проверьте GPTUNNEL_API_KEY в .env.', 'GPT Tunnel rejected the key. Check GPTUNNEL_API_KEY in .env.'],
  ASTRA_NOT_FOUND: ['В доступном каталоге нет единственной GPT-6 Astra. Выберите модель из каталога и явно задайте её ID в .env.', 'The catalog has no unique GPT-6 Astra. Choose an available model and explicitly set its ID in .env.'],
  MODEL_UNAVAILABLE: ['Указанная модель отсутствует в доступном каталоге. Выберите точный ID в .env.', 'The configured model is absent from your catalog. Choose an exact ID in .env.'],
  MODEL_DEPRECATED: ['Модель снята с обслуживания. Выберите замену в .env — автоматической подмены нет.', 'This model is retired. Choose a replacement in .env; no automatic substitution.'],
  MODEL_SUBSTITUTED: ['Провайдер сообщил о подмене модели. Ответ отклонён. Выберите замену в .env.', 'The provider substituted a different model. The response was rejected. Choose a replacement in .env.'],
  MODEL_FORBIDDEN: ['У ключа нет доступа к выбранной модели.', 'Your key has no access to this model.'],
  API_BALANCE: ['На балансе GPT Tunnel недостаточно средств.', 'Your GPT Tunnel balance is insufficient.'],
  API_TIMEOUT: ['Модель не ответила вовремя. Попробуйте ещё раз.', 'The model timed out. Please try again.'],
  API_RATE_LIMIT: ['Лимит запросов GPT Tunnel. Подождите минуту.', 'GPT Tunnel rate limit. Wait a minute.'],
  LOCAL_RATE_LIMIT: ['Локальный лимит запросов. Подождите минуту.', 'Local request limit. Wait a minute.'],
  INVALID_AI_JSON: ['Некорректный ответ AI. Никакие действия не применены.', 'Invalid AI response. No actions were applied.'],
  INVALID_AI_SCHEMA: ['Ответ AI не прошёл проверку структуры.', 'The AI response failed schema validation.'],
  CONSENT_REQUIRED: ['Разрешите анализ в настройках после ознакомления с передачей данных.', 'Review the data disclosure and enable analysis in Settings.'],
  EXTENSION_REQUIRED: ['Эта функция доступна в установленном расширении Chrome.', 'This feature requires the installed Chrome extension.'],
  PAGE_UNAVAILABLE: ['Эта страница недоступна для анализа или исключена в настройках.', 'This page is unavailable or excluded in Settings.'],
  PERMISSION_DENIED: ['Доступ к сайту не предоставлен. Можно продолжить без чтения текста.', 'Site access was not granted. You can continue without reading page text.'],
  WORK_TAB_CLOSED: ['Рабочая вкладка закрыта или изменилась. Выберите материал во «Вкладках».', 'The work tab is closed or has changed. Select a resource in Tabs.'],
  TABS_CHANGED: ['Состав вкладок изменился. Запросите предложение групп ещё раз.', 'Your tabs have changed. Request a new grouping proposal.'],
  STALE_RESPONSE: ['Контекст изменился. Запросите подсказку ещё раз.', 'The context changed. Request a new suggestion.'],
  SESSION_ALREADY_RUNNING: ['Сначала завершите текущий сеанс.', 'Finish the current session first.'],
  INVALID_SESSION: ['Введите цель и длительность от 1 до 480 минут.', 'Enter a goal and a duration between 1 and 480 minutes.'],
  NO_SESSION: ['Сначала запустите сеанс фокуса.', 'Start a focus session first.'],
};
export function errorText(code: string, ru: boolean) { return errors[code]?.[ru ? 0 : 1] || (ru ? `Не удалось выполнить действие (${code}). Попробуйте ещё раз.` : `Action failed (${code}). Please try again.`); }
