const errors: Record<string, string> = {
  AI_NOT_CONNECTED: 'AI is not connected. Add your key to the local .env and restart the server.',
  PAIRING_REQUIRED: 'Enter the connection token from .local/pairing.txt in Settings.',
  SERVER_OFFLINE: 'Local server is unavailable. Run npm run server.',
  API_KEY_INVALID: 'GPT Tunnel rejected the key. Check GPTUNNEL_API_KEY in .env.',
  ASTRA_NOT_FOUND: 'The catalog has no unique GPT-6 Astra. Choose an available model and explicitly set its ID in .env.',
  MODEL_UNAVAILABLE: 'The configured model is absent from your catalog. Choose an exact ID in .env.',
  MODEL_DEPRECATED: 'This model is retired. Choose a replacement in .env; no automatic substitution.',
  MODEL_SUBSTITUTED: 'The provider substituted a different model. The response was rejected. Choose a replacement in .env.',
  MODEL_FORBIDDEN: 'Your key has no access to this model.',
  API_BALANCE: 'Your GPT Tunnel balance is insufficient.',
  API_TIMEOUT: 'The model timed out. Please try again.',
  API_RATE_LIMIT: 'GPT Tunnel rate limit. Wait a minute.',
  LOCAL_RATE_LIMIT: 'Local request limit. Wait a minute.',
  INVALID_AI_JSON: 'Invalid AI response. No actions were applied.',
  INVALID_AI_SCHEMA: 'The AI response failed schema validation.',
  CONSENT_REQUIRED: 'Review the data disclosure and enable analysis in Settings.',
  EXTENSION_REQUIRED: 'This feature requires the installed Chrome extension.',
  PAGE_UNAVAILABLE: 'This page is unavailable or excluded in Settings.',
  PERMISSION_DENIED: 'Site access was not granted. You can continue without reading page text.',
  WORK_TAB_CLOSED: 'The work tab is closed or has changed. Select a resource in Tabs.',
  TABS_CHANGED: 'Your tabs have changed. Request a new grouping proposal.',
  STALE_RESPONSE: 'The context changed. Request a new suggestion.',
  SESSION_ALREADY_RUNNING: 'Finish the current session first.',
  INVALID_SESSION: 'Enter a goal and a duration between 1 and 480 minutes.',
  NO_SESSION: 'Start a focus session first.',
};
export function errorText(code: string) { return errors[code] || `Action failed (${code}). Please try again.`; }
