import { useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, BarChart3, Check, CheckCheck, ChevronRight, Coffee, Copy, ExternalLink, FileText, Focus, Layers, Leaf, ListTodo, LoaderCircle, LockKeyhole, Pause, Pencil, Play, Plus, RotateCcw, Settings2, ShieldCheck, Sparkles, Square, Target, Trash2, X } from 'lucide-react';
import { initialState, type AppState, type Task, type Session } from '../shared/types';
import { settle } from '../shared/engine';
import { normalizeSites } from '../shared/privacy';
import { send, subscribe, isExtension, grantCurrentSite } from './bridge';
import { errorText } from './errors';
import './panel.css';

type Section = 'focus' | 'tasks' | 'tabs' | 'stats' | 'settings';
type TabItem = { id: number; title: string; url: string; active: boolean; pinned: boolean; groupId: number };
const time = (ms: number) => `${Math.floor(Math.max(0, ms) / 60000).toString().padStart(2, '0')}:${Math.floor(Math.max(0, ms) / 1000 % 60).toString().padStart(2, '0')}`;
const minutes = (ms: number) => Math.round(ms / 60000);
const icons = { focus: Focus, tasks: ListTodo, tabs: Layers, stats: BarChart3, settings: Settings2 };
function App() {
  const [state, setState] = useState<AppState>(initialState); const [section, setSection] = useState<Section>('focus');
  const [now, setNow] = useState(Date.now()); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [goal, setGoal] = useState(''); const [taskId, setTaskId] = useState(''); const [duration, setDuration] = useState(25); const [editGoal, setEditGoal] = useState(false);
  const [editor, setEditor] = useState<Partial<Task> | null>(null); const [tabs, setTabs] = useState<TabItem[]>([]); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<number[]>([]);
  const [confirmClear, setConfirmClear] = useState(false); const [confirmDuplicates, setConfirmDuplicates] = useState(false);
  const [token, setToken] = useState(''); const [sites, setSites] = useState(''); const [step, setStep] = useState(''); const [granted, setGranted] = useState('');
  const ru = state.settings.language === 'ru'; const t = (r: string, e: string) => ru ? r : e;
  const s: Session | null = state.session ? settle(structuredClone(state.session), now) : null;
  const active = !!s && s.phase !== 'finished'; const running = s?.phase === 'running';
  const nav: [Section, string][] = [['focus', t('Фокус', 'Focus')], ['tasks', t('Задачи', 'Tasks')], ['tabs', t('Вкладки', 'Tabs')], ['stats', t('Статистика', 'Insights')], ['settings', t('Настройки', 'Settings')]];
  useEffect(() => { const load = () => { void send('GET').then(setState).catch(e => setError(e.message)); }; load(); const unsub = subscribe(load); const tick = setInterval(() => setNow(Date.now()), 1000); return () => { unsub(); clearInterval(tick); }; }, []);
  useEffect(() => { document.documentElement.lang = ru ? 'ru' : 'en'; }, [ru]);
  useEffect(() => { if (state.taskDraft) { setEditor(state.taskDraft); setSection('tasks'); } }, [state.taskDraft?.title, state.taskDraft?.selectedText]);
  useEffect(() => { if (section === 'settings') { setSites(state.settings.excludedSites.join('\n')); setToken(state.settings.pairToken); } }, [section]);
  useEffect(() => { if (section === 'tabs') void send('LIST_TABS').then(setTabs).catch(e => setError(e.message)); }, [section]);
  useEffect(() => { if (!notice) return; const timeout = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timeout); }, [notice]);
  async function act(type: string, payload: Record<string, unknown> = {}) {
    setBusy(type); setError('');
    try { const result = await send(type, payload); setState(await send('GET')); if (['CLOSE_DUPLICATES', 'APPLY_GROUPS'].includes(type)) { setTabs(await send('LIST_TABS')); setSelected([]); } return result; }
    catch (e) { setError((e as Error).message); return undefined; }
    finally { setBusy(''); }
  }
  const settings = (value: object) => act('SETTINGS', { settings: value });
  function selectTask(id: string) { setTaskId(id); const task = state.tasks.find(t => t.id === id); if (task) setGoal(task.title); }
  function focusTask(task: Task) { setGoal(task.title); setTaskId(task.id); setSection('focus'); if (active) setEditGoal(true); }
  const assessment = state.assessment;
  const stateLabel = assessment?.category === 'aligned' ? t('По делу', 'On track') : assessment?.category === 'distracting' ? t('Возможное отвлечение', 'Possible distraction') : t('Недостаточно контекста', 'Not enough context');
  const taskCount = state.tasks.filter(x => x.status !== 'done').length;
  const totalFocus = [...state.history, ...(s ? [s] : [])].reduce((n, x) => n + x.totals.aligned + x.totals.distracting + x.totals.unknown, 0);
  const tabCandidates = tabs.filter(x => !x.active && !x.pinned && /^https?:/.test(x.url) && tabs.some(other => other.url === x.url && other.id !== x.id && (other.active || other.pinned || other.id < x.id)));
  const countDone = state.tasks.filter(x => x.status === 'done').length;
  return <div className={`app-shell ${isExtension ? 'extension' : 'preview'}`}>
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); setSection('focus'); }}><span className="brand-mark"><Focus size={24} strokeWidth={2.5} /></span><span>focus<span className="brand-light">tab</span><small>AI</small></span></a>
      <div className="sidebar-label">{t('ВАШЕ ПРОСТРАНСТВО', 'YOUR SPACE')}</div>
      <nav aria-label={t('Разделы', 'Sections')}>{nav.map(([id, label]) => { const Icon = icons[id]; return <button key={id} className={`nav-item ${section === id ? 'selected' : ''}`} onClick={() => setSection(id)} aria-current={section === id ? 'page' : undefined} title={label}><Icon size={19} /><span>{label}</span>{id === 'tasks' && taskCount > 0 && <small>{taskCount}</small>}{id === 'focus' && running && <i />}</button>; })}</nav>
      <div className="sidebar-bottom"><div className="little-plant" aria-hidden="true"><Leaf size={34} /><span>✳</span></div><h3>{t('Одна цель за раз.', 'One thing at a time.')}</h3><p>{t('Оставьте немного места для важного.', 'Make a little room for what matters.')}</p><div className="local-note"><ShieldCheck size={14} />{t('Ваши данные · ваш контроль', 'Your data · your control')}</div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><span className="breadcrumb">{t('Моё пространство', 'My workspace')}<ChevronRight size={13} /><strong>{nav.find(n => n[0] === section)?.[1]}</strong></span><div className="topbar-actions"><button className={`connection-dot ${state.ai.connected ? 'online' : ''}`} onClick={() => setSection('settings')}><i />{state.ai.connected ? state.ai.model : t('AI не подключён', 'AI not connected')}</button><button className="language-button" onClick={() => settings({ language: ru ? 'en' : 'ru' })} aria-label={t('Switch to English', 'Переключить на русский')}>{ru ? 'EN' : 'RU'}</button></div></header>
      <main>
        {!isExtension && <div className="preview-note"><span><Focus size={15} />{t('Веб-предпросмотр', 'Web preview')}</span>{t('Таймер и задачи сохраняются здесь. Для анализа страниц и управления вкладками установите расширение.', 'Timer and tasks are saved here. Install the extension to analyze pages and manage browser tabs.')}</div>}
        {error && <div role="alert" className="alert error"><span>{errorText(error, ru)}</span><button className="icon-button" onClick={() => setError('')} aria-label={t('Закрыть', 'Dismiss')}><X size={16} /></button></div>}
        {notice && <div role="status" className="alert success"><Check size={16} />{notice}</div>}
        {section === 'focus' && <>
          <div className="page-heading"><div><div className="eyebrow"><span />{t('МЕНЬШЕ ШУМА. БОЛЬШЕ СМЫСЛА.', 'LESS NOISE. MORE INTENTION.')}</div><h1>{active ? t('Выделите время важному.', 'A little room to focus.') : t('С чего начнём?', 'What matters today?')}</h1><p>{t('Одна задача, немного внимания — и вы уже на пути.', 'One task, a little attention. You’re on your way.')}</p></div><span className="heading-spark" aria-hidden="true">✳</span></div>
          <div className="focus-layout"><div className="focus-main">
            <section className="card timer-card">
              <div className="card-top"><span className="kicker"><Focus size={15} />{t('СЕАНС ФОКУСА', 'FOCUS SESSION')}</span><span className={`pill ${running ? 'green' : ''}`}>{s?.away && running ? t('Вы отошли', 'Away') : s?.phase === 'break' ? t('Перерыв', 'On a break') : s?.phase === 'paused' ? t('На паузе', 'Paused') : s?.phase === 'ready' ? t('Готовы продолжить', 'Ready to return') : running ? t('В процессе', 'In progress') : s?.phase === 'finished' ? t('Завершён', 'Finished') : t('Ваш темп', 'Your pace')}</span></div>
              <div className="timer-garden"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="orbit-leaf"><Leaf size={23} /></span><span className="orbit-star">✧</span><div className="timer-center"><span className="timer-caption">{s?.phase === 'break' ? t('ВРЕМЯ ВЫДОХНУТЬ', 'A MOMENT TO BREATHE') : t('ВРЕМЯ ДЛЯ ВАЖНОГО', 'TIME FOR WHAT MATTERS')}</span><div className="timer-digits" role="timer" aria-label={t('Осталось времени', 'Time remaining')}>{time(s?.phase === 'break' ? (s.breakUntil || now) - now : active ? s!.remainingMs : duration * 60000)}</div><span className="timer-whisper">{running ? t('Не спешите. Вы здесь.', 'No rush. You’re here.') : t('Маленький шаг — тоже шаг.', 'A small step is still a step.')}</span></div></div>
              {(!active || editGoal) ? <form className="goal-form" onSubmit={async e => { e.preventDefault(); const result = await act(active ? 'GOAL' : 'START', { goal, taskId, minutes: duration }); if (result) setEditGoal(false); }}>
                <label htmlFor="goal">{t('На чём хотите сосредоточиться?', 'What would you like to focus on?')}</label><textarea id="goal" required maxLength={1000} value={goal} onChange={e => setGoal(e.target.value)} placeholder={t('Например, изучить авторизацию в React и собрать пример', 'For example, learn React authentication and build an example')} rows={2} />
                <select aria-label={t('Активная задача', 'Active task')} value={taskId} onChange={e => selectTask(e.target.value)}><option value="">{t('Своя цель · без задачи', 'Custom goal · no task')}</option>{state.tasks.filter(t => t.status !== 'done').map(task => <option key={task.id} value={task.id}>{task.title}</option>)}</select>
                {!active && <div className="duration-row"><span>{t('Минуты', 'Minutes')}</span><div className="segmented">{[25, 50].map(m => <button key={m} type="button" className={duration === m ? 'on' : ''} onClick={() => setDuration(m)}>{m}</button>)}<input aria-label={t('Своя длительность в минутах', 'Custom duration in minutes')} type="number" min={1} max={480} value={duration} onChange={e => setDuration(Number(e.target.value))} /></div></div>}
                <button type="submit" className="btn primary full" disabled={!!busy || !goal.trim()}>{busy === 'START' ? <LoaderCircle className="spin" size={17} /> : <Play size={16} fill="currentColor" />}{active ? t('Обновить цель', 'Update goal') : t('Начать фокус', 'Start focusing')}<span className="button-end">↗</span></button>
                {editGoal && <button type="button" className="text-button" onClick={() => setEditGoal(false)}>{t('Отмена', 'Cancel')}</button>}
              </form> : <div className="active-controls"><div className="active-goal"><Target size={19} /><div><span>{t('ВАША ЦЕЛЬ', 'YOUR GOAL')}</span><h2>{s?.goal}</h2></div><button className="icon-button" aria-label={t('Изменить цель', 'Edit goal')} onClick={() => { setGoal(s!.goal); setTaskId(s!.taskId); setEditGoal(true); }}><Pencil size={16} /></button></div><div className="button-row"><button className="btn primary" onClick={() => act(running ? 'PAUSE' : 'RESUME')}>{running ? <Pause size={16} /> : <Play size={16} />}{running ? t('Пауза', 'Pause') : t('Продолжить', 'Resume')}</button>{s?.phase !== 'break' && <button className="btn secondary" onClick={() => act('BREAK', { minutes: state.settings.breakMinutes })}><Coffee size={16} />{t('Перерыв', 'Break')} · {state.settings.breakMinutes}{t('м', 'm')}</button>}</div></div>}
              <div className="timer-footer"><ShieldCheck size={13} />{active ? t('Сеанс сохранён. Панель можно закрыть.', 'Session saved. You can close this panel.') : t('Наблюдение начнётся только вместе с сеансом.', 'Observation starts only when you start a session.')}</div>
            </section>
            {s?.resumeCard && <section className="card resume-card"><div className="kicker"><RotateCcw size={16} />{t('ПРОДОЛЖИТЬ С ТОГО МЕСТА', 'PICK UP WHERE YOU LEFT OFF')}</div><h2>{s.goal}</h2><p className="small-label">{t('Сохранённые факты', 'Saved facts')}</p><p>{s.lastConfirmedStep ? `${t('Ваш последний подтверждённый шаг:', 'Your last confirmed step:')} ${s.lastConfirmedStep}` : t('Последний шаг ещё не подтверждён.', 'No last step has been confirmed.')}</p>{s.workTabs.length > 0 && <ul className="resource-list">{s.workTabs.map(tab => <li key={tab.tabId}><FileText size={14} />{tab.title}</li>)}</ul>}<p className="muted">{t('Открытая вкладка не означает, что материал прочитан.', 'An open tab does not mean its contents were read.')}</p><button className="btn primary" onClick={() => act('RETURN')}><ArrowRight size={16} />{t('К рабочим вкладкам', 'Back to work tabs')}</button><button className="text-button" onClick={() => act('AI', { kind: 'next' })}>{t('Предложить следующий шаг', 'Suggest the next step')}</button></section>}
            <div className="gentle-note"><span>✳</span><p>{t('Внимание — это практика, а не идеальный результат.', 'Attention is a practice, not a perfect score.')}<small>{t('Можно отвлечься. Можно вернуться.', 'It’s okay to wander. You can always return.')}</small></p></div>
          </div><div className="focus-aside">
            <section className={`card context-card ${assessment?.category || ''}`}><div className="card-top"><span className="kicker"><Sparkles size={15} />{t('РЯДОМ С ВАШИМ ФОКУСОМ', 'ALONGSIDE YOUR FOCUS')}</span><span className="tiny-dot" /></div>
              <div className="context-symbol">{assessment?.category === 'aligned' ? <Check size={25} /> : assessment?.category === 'distracting' ? <Leaf size={25} /> : <Sparkles size={25} />}</div>
              <h2>{state.ai.code === 'ANALYZING' || state.pendingAt ? t('Разбираемся в контексте…', 'Finding the context…') : !active ? t('Сначала — ваша цель.', 'Your goal comes first.') : !state.settings.consent ? t('Анализ выключен', 'Analysis is off') : !state.ai.connected && !assessment ? t('AI не подключён', 'AI is not connected') : stateLabel}</h2>
              <p>{state.pendingAt ? t('Дадим странице около 8 секунд. Случайная вкладка — ещё не отвлечение.', 'Giving this page about 8 seconds. A passing tab isn’t a distraction.') : assessment?.reason || (!active ? t('Когда начнётся сеанс, здесь появится контекст текущей страницы и спокойная подсказка.', 'Start a session to see context about your current page and a gentle suggestion.') : !state.settings.consent ? t('Вы решаете, когда делиться контекстом страницы с AI.', 'You decide when to share page context with AI.') : t('Таймер продолжает работать. Для оценок подключите локальный сервер и модель.', 'The timer keeps running. Connect the local server and model for assessments.'))}</p>
              {state.page && <div className="page-source"><span><FileText size={14} />{state.page.title || t('Без названия', 'Untitled')}</span><small>{new URL(state.page.url).hostname}</small></div>}
              {assessment?.nextStep && <div className="next-step"><span>{t('ПРЕДЛОЖЕНИЕ', 'SUGGESTION')}</span><p>{assessment.nextStep}</p><button className="text-button" onClick={() => act('CONFIRM_STEP', { step: assessment.nextStep })}><CheckCheck size={14} />{t('Я сделал(а) этот шаг', 'I completed this step')}</button></div>}
              {running && state.page && <div className="context-actions">{assessment?.category === 'distracting' && <button className="btn primary full" onClick={() => act('RETURN')}><ArrowRight size={16} />{t('Вернуться к работе', 'Back to work')}</button>}<div className="button-row"><button className="btn secondary" onClick={() => act('CORRECT')}><Check size={15} />{t('Это по делу', 'This is relevant')}</button><button className="btn secondary" onClick={() => act('BREAK', { minutes: 5 })}><Coffee size={15} />5 {t('минут', 'minutes')}</button></div><button className="text-button" disabled={!!busy} onClick={() => act('AI', { kind: 'next' })}><Sparkles size={14} />{busy === 'AI' ? t('Думаем…', 'Thinking…') : t('Помоги продолжить', 'Help me continue')}</button></div>}
              {(!state.settings.consent || !state.ai.connected) && <button className="text-button" onClick={() => setSection('settings')}>{t('Настроить AI', 'Set up AI')}<ArrowUpRight size={15} /></button>}
              {assessment?.source === 'user' && <span className="user-confirmed"><CheckCheck size={12} />{t('Ваша поправка · только этот контекст', 'Your correction · this context only')}</span>}
            </section>
            <section className="card up-next"><div className="card-top"><span className="kicker"><ListTodo size={15} />{t('ПОД РУКОЙ', 'WITHIN REACH')}</span><button className="icon-button" aria-label={t('Добавить задачу', 'Add task')} onClick={() => { setEditor({}); setSection('tasks'); }}><Plus size={17} /></button></div>{state.tasks.filter(x => x.status !== 'done').slice(0, 3).map(task => <button className="mini-task" key={task.id} onClick={() => focusTask(task)}><span className="task-circle" /><span>{task.title}</span><ArrowUpRight size={14} /></button>)}{!taskCount && <div className="small-empty"><p>{t('Освободите голову.', 'Free up some headspace.')}</p><span>{t('Запишите первую задачу, чтобы не держать её в памяти.', 'Write down your first task so you don’t have to keep it in mind.')}</span><button className="text-button" onClick={() => { setEditor({}); setSection('tasks'); }}><Plus size={14} />{t('Добавить задачу', 'Add a task')}</button></div>}</section>
            <section className="today-card"><div><span>{t('ВРЕМЯ СЕАНСОВ', 'SESSION TIME')}</span><strong>{minutes(totalFocus)} <small>{t('мин', 'min')}</small></strong></div><div className="today-divider" /><div><span>{t('ЗАДАЧ ГОТОВО', 'TASKS DONE')}</span><strong>{countDone}<small> <CheckCheck size={17} /></small></strong></div><p>{t('Реальные события. Без оценки вашей продуктивности.', 'Real events. No productivity score.')}</p></section>
          </div></div>
        </>}
        {section === 'tasks' && <><PageHeading title={t('Меньше в голове.', 'A little less on your mind.')} description={t('Соберите задачи здесь. Выберите одну для фокуса.', 'Keep your tasks here. Pick one to focus on.')} kicker={t('ЗАДАЧИ', 'YOUR TASKS')} /><div className="section-toolbar"><span>{taskCount} {t('впереди', 'to go')} · {countDone} {t('готово', 'done')}</span><div className="button-row"><button className="btn secondary" disabled={!!busy} onClick={() => act('AI', { kind: 'task' })}><Sparkles size={16} />{t('Из страницы', 'From page')}</button><button className="btn primary" onClick={() => setEditor({})}><Plus size={16} />{t('Новая задача', 'New task')}</button></div></div>
          {editor && <TaskEditor key={editor.id || editor.title || 'new'} task={editor} ru={ru} busy={!!busy} onClose={() => { setEditor(null); void act('CLEAR_DRAFT'); }} onAI={state.taskDraft?.selectedText ? () => { void act('AI', { kind: 'task' }); } : undefined} onSave={async task => { if (await act('SAVE_TASK', { task })) setEditor(null); }} />}
          {!state.tasks.length && !editor && <Empty icon={<ListTodo size={35} />} title={t('Первый шаг начинается с записи.', 'A first step starts with a note.')} text={t('Добавьте задачу вручную или выделите текст на странице и выберите FocusTab в контекстном меню Chrome.', 'Add a task, or select text on a page and choose FocusTab in Chrome’s context menu.')} />}
          <div className="task-list">{state.tasks.map(task => <article className={`card task-row ${task.status === 'done' ? 'done' : ''}`} key={task.id}><button className={`check-button ${task.status === 'done' ? 'checked' : ''}`} aria-label={task.status === 'done' ? t('Вернуть в запланированное', 'Mark as planned') : t('Отметить готовой', 'Mark done')} onClick={() => act('SAVE_TASK', { task: { ...task, status: task.status === 'done' ? 'planned' : 'done' } })}>{task.status === 'done' && <Check size={15} />}</button><div className="task-detail"><h3>{task.title}</h3><div className="task-meta"><span className={`pill ${task.status === 'doing' ? 'green' : ''}`}>{task.status === 'doing' ? t('В работе', 'In progress') : task.status === 'done' ? t('Готово', 'Done') : t('Запланировано', 'Planned')}</span>{task.due && <span>{task.due}</span>}{task.source && <a href={task.source} target="_blank" rel="noreferrer"><ExternalLink size={12} />{t('Источник', 'Source')}</a>}</div>{task.steps.length > 0 && <ol>{task.steps.map((step, i) => <li key={i}>{step}</li>)}</ol>}</div><div className="task-actions"><button className="icon-button" title={t('Редактировать', 'Edit')} aria-label={t('Редактировать', 'Edit')} onClick={() => setEditor(task)}><Pencil size={16} /></button>{task.status !== 'done' && <button className="icon-button" title={t('Выбрать для фокуса', 'Focus on this')} aria-label={t('Выбрать для фокуса', 'Focus on this')} onClick={() => focusTask(task)}><Focus size={18} /></button>}</div></article>)}</div>
        </>}
        {section === 'tabs' && <><PageHeading title={t('Место для каждой мысли.', 'A home for every thought.')} description={t('Вкладки текущего окна. Группировки — только с вашего согласия.', 'Tabs in this window. Grouping always starts with your review.')} kicker={t('ВАШ БРАУЗЕР', 'YOUR BROWSER')} /><div className="section-toolbar"><input className="search-input" type="search" aria-label={t('Поиск вкладок', 'Search tabs')} placeholder={t('Найти вкладку…', 'Find a tab…')} value={search} onChange={e => setSearch(e.target.value)} /><button className="btn secondary" onClick={async () => setTabs(await send('LIST_TABS'))}><RotateCcw size={15} />{t('Обновить', 'Refresh')}</button></div><div className="button-row tab-tools"><button className="btn primary" disabled={!!busy || !tabs.length} onClick={() => act('AI', { kind: 'groups' })}><Sparkles size={16} />{t('Предложить группы', 'Suggest groups')}</button><span className="muted">{tabs.length} {t('вкладок', 'tabs')} · {tabCandidates.length} {t('точных дубликатов', 'exact duplicates')}</span></div>
          {state.groupDraft && <section className="card group-review"><div className="kicker">{t('ПРЕДЛОЖЕНИЕ AI · ПРОВЕРЬТЕ СОСТАВ', 'AI SUGGESTION · REVIEW MEMBERS')}</div>{state.groupDraft.map((g, i) => <div className="group-item" key={i}><h3><i style={{ background: g.color }} />{g.title}</h3><ul>{g.tabIds.map(id => <li key={id}>{tabs.find(t => t.id === id)?.title || `#${id}`}</li>)}</ul></div>)}<button className="btn primary" disabled={!!busy} onClick={() => act('APPLY_GROUPS')}><Layers size={16} />{t('Подтвердить и создать группы', 'Confirm & create groups')}</button></section>}
          {!tabs.length && <Empty icon={<Layers size={35} />} title={t('Здесь появятся ваши вкладки.', 'Your tabs will feel at home here.')} text={isExtension ? t('Откройте страницу в этом окне и обновите список.', 'Open a page in this window and refresh.') : t('Веб-предпросмотр не имеет доступа к вкладкам. Установите расширение Chrome.', 'The web preview cannot access your tabs. Install the Chrome extension.')} />}
          <div className="tab-list">{tabs.filter(tab => (tab.title + tab.url).toLowerCase().includes(search.toLowerCase())).map(tab => <article className="card tab-row" key={tab.id}>{tabCandidates.some(t => t.id === tab.id) ? <input type="checkbox" aria-label={t('Выбрать дубликат: ', 'Select duplicate: ') + tab.title} checked={selected.includes(tab.id)} onChange={e => setSelected(e.target.checked ? [...selected, tab.id] : selected.filter(id => id !== tab.id))} /> : <span className="tab-icon"><FileText size={18} /></span>}<button className="tab-title" onClick={() => act('ACTIVATE_TAB', { tabId: tab.id })}><strong>{tab.title}</strong><small>{tab.url ? (() => { try { return new URL(tab.url).hostname || tab.url; } catch { return ''; } })() : ''}</small></button>{tab.active && <span className="pill green">{t('Открыта', 'Active')}</span>}{tabCandidates.some(t => t.id === tab.id) && <Copy size={15} className="muted" />}</article>)}</div>
          {selected.length > 0 && <section className="card duplicate-review"><p>{t('Выбрано дубликатов:', 'Selected duplicates:')} {selected.length}. {t('Закрытые вкладки могут содержать несохранённые данные.', 'Selected tabs may contain unsaved data.')}</p>{confirmDuplicates ? <><ul>{tabs.filter(t => selected.includes(t.id)).map(t => <li key={t.id}>{t.title}</li>)}</ul><div className="button-row"><button className="btn danger" onClick={async () => { await act('CLOSE_DUPLICATES', { tabIds: selected }); setConfirmDuplicates(false); }}>{t('Закрыть выбранные вкладки', 'Close selected tabs')}</button><button className="btn secondary" onClick={() => setConfirmDuplicates(false)}>{t('Отмена', 'Cancel')}</button></div></> : <button className="btn secondary" onClick={() => setConfirmDuplicates(true)}><Trash2 size={15} />{t('Проверить перед закрытием', 'Review before closing')}</button>}</section>}
        </>}
        {section === 'stats' && <><PageHeading title={t('Замечайте свой ритм.', 'Notice your own rhythm.')} description={t('Наблюдения о сеансах. Продуктивность не сводится к времени на сайте.', 'Observations from your sessions. Time on a site isn’t proof of productivity.')} kicker={t('СТАТИСТИКА', 'YOUR INSIGHTS')} />{!s && !state.history.length ? <Empty icon={<BarChart3 size={35} />} title={t('Всё начинается с первого сеанса.', 'It starts with your first session.')} text={t('Здесь появятся реальные интервалы времени и отмеченные вами результаты.', 'Real time intervals and your confirmed outcomes will appear here.')} /> : <><div className="stats-grid"><Stat label={t('Время сеансов', 'Session time')} value={`${minutes(totalFocus)} ${t('мин', 'min')}`} /><Stat label={t('Перерывы', 'Breaks')} value={`${minutes([...state.history, ...(s ? [s] : [])].reduce((n, x) => n + x.totals.break, 0))} ${t('мин', 'min')}`} /><Stat label={t('Задач отмечено готовыми', 'Tasks marked done')} value={String(countDone)} /></div>{[...(s ? [s] : []), ...state.history].map(session => { const work = session.totals.aligned + session.totals.distracting + session.totals.unknown; return <section className="card session-report" key={session.id}><div className="card-top"><span className="kicker">{new Date(session.startedAt).toLocaleDateString(ru ? 'ru-RU' : 'en-US', { day: 'numeric', month: 'long' })}</span><span className="pill">{session.phase === 'finished' ? t('Завершён', 'Finished') : t('Текущий сеанс', 'Current session')}</span></div><h2>{session.goal}</h2><div className="distribution" aria-label={t('Распределение времени', 'Time distribution')}>{(['aligned', 'distracting', 'unknown'] as const).map(c => <span key={c} className={c} style={{ width: `${work ? session.totals[c] / work * 100 : 0}%` }} />)}</div><div className="time-legend">{(['aligned', 'distracting', 'unknown', 'break', 'away', 'paused'] as const).map((c, i) => <div key={c}><span><i className={c} />{[t('По делу', 'On track'), t('Возможное отвлечение', 'Possible distraction'), t('Не определено', 'Unclassified'), t('Перерыв', 'Break'), t('Отсутствие', 'Away'), t('Пауза / ожидание', 'Paused / waiting')][i]}</span><strong>{time(session.totals[c])}</strong></div>)}</div><div className="report-counts"><span>{session.reminders} {t('напоминаний', 'reminders')}</span><span>{session.returns} {t('возвратов к работе', 'returns to work')}</span></div>{session.summary && <div className="summary"><h3>{t('Факты по событиям', 'Facts from events')}</h3><ul>{session.summary.facts.map((f, i) => <li key={i}>{f}</li>)}</ul><h3>{t('Предложения AI', 'AI suggestions')}</h3><ul>{session.summary.suggestions.map((f, i) => <li key={i}>{f}</li>)}</ul></div>}{session.id === s?.id && <button className="text-button" disabled={!!busy} onClick={() => act('AI', { kind: 'summary' })}><Sparkles size={15} />{t('Краткий итог от AI', 'Get an AI recap')}</button>}</section>; })}</>}
          <section className="card usage-card"><div className="kicker"><Sparkles size={15} />{t('РАСХОД AI', 'AI USAGE')}</div><div className="usage-values"><div><span>{t('Токены', 'Tokens')}</span><strong>{state.usage.total_tokens ?? '—'}</strong></div><div><span>{t('Стоимость по данным провайдера', 'Cost reported by provider')}</span><strong>{state.usage.total_cost !== undefined ? `${state.usage.total_cost.toFixed(5)}` : '—'}</strong></div></div><p className="muted">{t('Показываем только возвращённые сервером данные. Пустое поле не означает нулевую стоимость.', 'Only data returned by the server is shown. An empty field does not mean zero cost.')}</p></section>
        </>}
        {section === 'settings' && <><PageHeading title={t('Ваш фокус. Ваши правила.', 'Your focus. Your rules.')} description={t('Контроль над данными и помощью остаётся у вас.', 'You stay in control of your data and your assistance.')} kicker={t('НАСТРОЙКИ', 'SETTINGS')} /><div className="settings-grid">
          <section className="card settings-card"><div className="kicker"><LockKeyhole size={16} />{t('ПОДКЛЮЧЕНИЕ AI', 'AI CONNECTION')}</div><h2>GPT Tunnel <span className="muted">/</span> GPT-6 Astra</h2><p>{t('Ключ модели хранится только в локальном .env сервера. Здесь нужен отдельный токен подключения из .local/pairing.txt.', 'Your model key stays in the server’s local .env. Enter the separate connection token from .local/pairing.txt here.')}</p><label htmlFor="pair-token">{t('Токен подключения к локальному серверу', 'Local server connection token')}</label><input id="pair-token" type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} placeholder={t('Не API-ключ GPT Tunnel', 'Not the GPT Tunnel API key')} /><div className="button-row"><button className="btn primary" disabled={!!busy} onClick={async () => { if (await settings({ pairToken: token })) await act('CONNECT'); }}>{busy === 'CONNECT' ? <LoaderCircle size={16} className="spin" /> : <Sparkles size={16} />}{t('Подключить и проверить', 'Connect & check')}</button></div><div className={`connection-status ${state.ai.connected ? 'success-text' : ''}`}>{state.ai.connected ? `${t('Модель доступна:', 'Model available:')} ${state.ai.model}` : errorText(state.ai.code === 'ANALYZING' || state.ai.code === 'READY' ? 'AI_NOT_CONNECTED' : state.ai.code, ru)}</div>{state.ai.available?.length ? <details><summary>{t('Доступные модели · выбор в GPTUNNEL_MODEL', 'Available models · choose in GPTUNNEL_MODEL')}</summary><ul>{state.ai.available.map(m => <li key={m}><code>{m}</code></li>)}</ul></details> : null}<p className="small-label">{t('Модель не заменяется автоматически. Доступность каталога не означает успешный ответ модели.', 'Models are never silently substituted. Catalog access does not verify a live model response.')}</p></section>
          <section className="card settings-card privacy-card"><div className="kicker"><ShieldCheck size={16} />{t('ДАННЫЕ И РАЗРЕШЕНИЯ', 'DATA & PERMISSIONS')}</div><h2>{t('Ровно столько, сколько нужно.', 'Just enough context.')}</h2><p>{t('При анализе через ваш локальный сервер в GPT Tunnel и модель передаются: цель, выбранная задача, заголовок, очищенный URL, время на странице, краткие события сеанса и ваши поправки. Группировка отправляет названия и очищенные адреса вкладок текущего окна; извлечение — выбранный текст.', 'Analysis sends your goal, selected task, page title, cleaned URL, time on page, recent session events and corrections through your local server to GPT Tunnel and the model. Grouping sends titles and cleaned URLs from this window; extraction sends selected text.')}</p><Toggle label={t('Разрешить анализ через AI', 'Allow AI analysis')} hint={t('Наблюдение — только в запущенном сеансе. Задачи и группировки — по нажатию.', 'Observation only during a running session. Tasks and grouping only on request.')} checked={state.settings.consent} onChange={v => settings({ consent: v })} /><Toggle label={t('Добавлять видимый текст страницы', 'Include visible page text')} hint={t('До 4 000 символов, без форм и полей ввода. Нужен отдельный доступ к сайту.', 'Up to 4,000 characters, excluding forms and inputs. Requires site permission.')} checked={state.settings.readText} onChange={v => settings({ readText: v })} /><button className="btn secondary" onClick={async () => { try { const host = await grantCurrentSite(); setGranted(host); setNotice(t('Доступ к сайту предоставлен.', 'Site access granted.')); if (isExtension) await settings({}); } catch (e) { setError((e as Error).message); } }}><Plus size={15} />{t('Разрешить доступ к текущему сайту', 'Allow access to current site')}</button>{granted && <p className="success-text">{granted}</p>}<label htmlFor="excluded-sites">{t('Исключённые сайты', 'Excluded sites')}</label><textarea id="excluded-sites" rows={3} value={sites} onChange={e => setSites(e.target.value)} placeholder="bank.example.com" /><p className="small-label">{t('По одному домену на строку. Поддомены тоже исключаются.', 'One domain per line. Subdomains are excluded too.')}</p><button className="text-button" onClick={async () => { await settings({ excludedSites: normalizeSites(sites) }); setNotice(t('Исключения сохранены.', 'Exclusions saved.')); }}><Check size={15} />{t('Сохранить исключения', 'Save exclusions')}</button></section>
          <section className="card settings-card"><div className="kicker"><Leaf size={16} />{t('КАК ВАМ ПОМОГАТЬ', 'HOW WE CAN HELP')}</div><div className="mode-options">{(['soft', 'strict'] as const).map(mode => <button key={mode} className={`mode-option ${state.settings.mode === mode ? 'chosen' : ''}`} onClick={() => settings({ mode })}><span>{mode === 'soft' ? <Leaf size={19} /> : <ShieldCheck size={19} />}<strong>{mode === 'soft' ? t('Мягко', 'Gentle') : t('Строго', 'Strict')}</strong><span className="radio-dot" /></span><p>{mode === 'soft' ? t('Спокойные напоминания и предложение вернуться.', 'Gentle reminders and an invitation to return.') : t('Временная шторка поверх отвлекающей страницы. Можно исправить оценку, сделать перерыв или остановиться.', 'A temporary cover over a distracting page. Correct it, take a break or stop anytime.')}</p></button>)}</div>{state.settings.mode === 'strict' && <p className="small-label">{t('Для шторки разрешите доступ к сайту выше. При недоступности AI шторка снимается; проверка соединения каждые 30 секунд, срок действия — 40 секунд.', 'Grant site access above for the cover. It clears if AI is unavailable; connection checks every 30 seconds, with a 40-second lease.')}</p>}<label htmlFor="break-minutes">{t('Длительность обычного перерыва, минут', 'Default break length, minutes')}</label><input id="break-minutes" type="number" min={1} max={120} value={state.settings.breakMinutes} onChange={e => settings({ breakMinutes: Number(e.target.value) })} /><label>{t('Язык интерфейса и подсказок', 'Interface and suggestion language')}</label><select value={state.settings.language} onChange={e => settings({ language: e.target.value })}><option value="ru">Русский</option><option value="en">English</option></select></section>
          <section className="card settings-card"><div className="kicker"><FileText size={16} />{t('ПОСЛЕДНИЙ ШАГ', 'LAST CONFIRMED STEP')}</div><p>{t('Запишите то, что действительно сделали. Это поможет вернуться после перерыва.', 'Write down what you actually completed. It helps you pick up after a break.')}</p><textarea aria-label={t('Подтверждённый шаг', 'Confirmed step')} rows={2} value={step} maxLength={600} onChange={e => setStep(e.target.value)} placeholder={s?.lastConfirmedStep || t('Например: создал компонент формы входа', 'For example: created a login form component')} /><button className="text-button" disabled={!s || !step.trim()} onClick={async () => { await act('CONFIRM_STEP', { step }); setNotice(t('Ваш шаг сохранён.', 'Your step is saved.')); }}><CheckCheck size={15} />{t('Подтвердить шаг', 'Confirm step')}</button><hr /><p>{t('Сеансы, задачи и поправки хранятся локально. Очистка удалит их и токен подключения из расширения.', 'Sessions, tasks and corrections are stored locally. Clearing removes them and the extension connection token.')}</p>{confirmClear ? <div className="button-row"><button className="btn danger" onClick={async () => { await act('CLEAR_DATA'); setConfirmClear(false); setSection('focus'); }}>{t('Удалить локальные данные', 'Delete local data')}</button><button className="btn secondary" onClick={() => setConfirmClear(false)}>{t('Отмена', 'Cancel')}</button></div> : <button className="text-button danger-text" onClick={() => setConfirmClear(true)}><Trash2 size={14} />{t('Очистить локальные данные', 'Clear local data')}</button>}</section>
        </div></>}
        <footer className="page-footer"><span><Focus size={13} />FocusTab AI</span><span>{t('Меньше открытых мыслей.', 'Fewer open loops.')} <Leaf size={12} /></span></footer>
      </main>
      {active && <div className="session-dock"><span><i className={running ? 'pulsing' : ''} /><strong>{time(s!.phase === 'break' ? (s!.breakUntil || now) - now : s!.remainingMs)}</strong><span>{s!.goal}</span></span><button onClick={() => act('STOP')}><Square size={13} />{t('Остановить сеанс', 'Stop session')}</button></div>}
    </div>
  </div>;
}
function PageHeading({ title, description, kicker }: { title: string; description: string; kicker: string }) { return <div className="page-heading"><div><div className="eyebrow"><span />{kicker}</div><h1>{title}</h1><p>{description}</p></div><span className="heading-spark" aria-hidden="true">✳</span></div>; }
function Empty({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <div className="empty-state"><div>{icon}</div><h2>{title}</h2><p>{text}</p></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="card stat"><span>{label}</span><strong>{value}</strong></div>; }
function Toggle({ label, hint, checked, onChange }: { label: string; hint: string; checked: boolean; onChange: (v: boolean) => void }) { return <label className="toggle-row"><span><strong>{label}</strong><small>{hint}</small></span><input role="switch" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /></label>; }
function TaskEditor({ task, ru, busy, onSave, onClose, onAI }: { task: Partial<Task>; ru: boolean; busy: boolean; onSave: (task: Partial<Task>) => void; onClose: () => void; onAI?: () => void }) {
  const [title, setTitle] = useState(task.title || ''); const [steps, setSteps] = useState(task.steps?.join('\n') || ''); const [due, setDue] = useState(task.due || ''); const [source, setSource] = useState(task.source || ''); const [status, setStatus] = useState(task.status || 'planned');
  const t = (r: string, e: string) => ru ? r : e;
  function submit(e: FormEvent) { e.preventDefault(); onSave({ ...task, title, steps: steps.split('\n').map(x => x.trim()).filter(Boolean).slice(0, 8), source, due, status }); }
  return <form className="card task-editor" onSubmit={submit}><div className="card-top"><h2>{task.id ? t('Поправим задачу', 'Refine your task') : t('Новая задача', 'A new task')}</h2><button className="icon-button" type="button" onClick={onClose} aria-label={t('Закрыть редактор', 'Close editor')}><X size={18} /></button></div><p className="muted">{t('Проверьте формулировку и шаги перед сохранением.', 'Review the title and steps before saving.')}</p><label htmlFor="task-title">{t('Название', 'Title')}</label><input id="task-title" autoFocus required maxLength={180} value={title} onChange={e => setTitle(e.target.value)} /><label htmlFor="task-steps">{t('Краткие шаги · по одному на строку', 'Short steps · one per line')}</label><textarea id="task-steps" rows={3} value={steps} onChange={e => setSteps(e.target.value)} /><div className="form-columns"><div><label htmlFor="task-status">{t('Статус', 'Status')}</label><select id="task-status" value={status} onChange={e => setStatus(e.target.value as Task['status'])}><option value="planned">{t('Запланировано', 'Planned')}</option><option value="doing">{t('В работе', 'In progress')}</option><option value="done">{t('Готово', 'Done')}</option></select></div><div><label htmlFor="task-due">{t('Срок · необязательно', 'Due date · optional')}</label><input id="task-due" type="date" value={due} onChange={e => setDue(e.target.value)} /></div></div><label htmlFor="task-source">{t('Ссылка на источник', 'Source link')}</label><input id="task-source" type="url" value={source} onChange={e => setSource(e.target.value)} placeholder="https://…" /><div className="button-row"><button className="btn primary" type="submit" disabled={busy || !title.trim()}><Check size={16} />{t('Сохранить задачу', 'Save task')}</button>{onAI && <button className="btn secondary" type="button" disabled={busy} onClick={onAI}><Sparkles size={15} />{t('Сформулировать с AI', 'Refine with AI')}</button>}</div></form>;
}
createRoot(document.getElementById('root')!).render(<App />);
