import { MissionView } from './mission-view';
import { AmbiguousView } from './ambiguous-view';
import { useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, BarChart3, Check, CheckCheck, ChevronRight, Coffee, Copy, ExternalLink, FileText, Focus, Layers, Leaf, ListTodo, LoaderCircle, LockKeyhole, Pause, Pencil, Play, Plus, RotateCcw, Settings2, ShieldCheck, Sparkles, Square, Target, Trash2, X } from 'lucide-react';
import { initialState, type AppState, type Task, type Session } from '../shared/types';
import { settle } from '../shared/engine';
import { normalizeSites } from '../shared/privacy';
import { send, subscribe, isExtension, grantCurrentSite } from './bridge';
import { errorText } from './errors';
import logo from '../../public/brand/tabby/tabby-logo.svg';
import cat from '../../public/brand/tabby/tabby-mark-task.svg';
import sidebarCat from '../../public/brand/tabby/tabby-mark-sidebar.svg';
import { ProjectsView, WorkspaceSettings, AdvancedInsights } from './projects-view';
import './panel.css';
import { CalendarDays, MessageCircle } from 'lucide-react';
import { ChatPanel, GooglePanel } from './workspace-panels';

type Section = 'mission' | 'ambiguous' | 'focus' | 'projects' | 'tasks' | 'tabs' | 'stats' | 'settings' | 'google' | 'chat';
type TabItem = { id: number; title: string; url: string; active: boolean; pinned: boolean; groupId: number };
const time = (ms: number) => `${Math.floor(Math.max(0, ms) / 60000).toString().padStart(2, '0')}:${Math.floor(Math.max(0, ms) / 1000 % 60).toString().padStart(2, '0')}`;
const minutes = (ms: number) => Math.round(ms / 60000);
const icons = { mission: Target, ambiguous: MessageCircle, projects: Layers, focus: Focus, tasks: ListTodo, tabs: Layers, stats: BarChart3, settings: Settings2, google: CalendarDays, chat: MessageCircle };
function App() {
  const [state, setState] = useState<AppState>(initialState); const [section, setSection] = useState<Section>('mission');
  const [now, setNow] = useState(Date.now()); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [goal, setGoal] = useState(''); const [taskId, setTaskId] = useState(''); const [duration, setDuration] = useState(25); const [editGoal, setEditGoal] = useState(false);
  const [editor, setEditor] = useState<Partial<Task> | null>(null); const [tabs, setTabs] = useState<TabItem[]>([]); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<number[]>([]);
  const [projectId, setProjectId] = useState('');
  const [confirmClear, setConfirmClear] = useState(false); const [confirmDuplicates, setConfirmDuplicates] = useState(false);
  const [token, setToken] = useState(''); const [sites, setSites] = useState(''); const [step, setStep] = useState(''); const [granted, setGranted] = useState('');
  const [siteAccess, setSiteAccess] = useState<boolean | null>(null);
  const s: Session | null = state.session ? settle(structuredClone(state.session), now) : null;
  const active = !!s && s.phase !== 'finished'; const running = s?.phase === 'running';
  const nav: [Section, string][] = [['mission', 'Mission'], ['focus', 'Focus'], ['tasks', 'Tasks'], ['ambiguous', 'Ambiguous'], ['google', 'Calendar & mail'], ['chat', 'AI chat'], ['projects', 'Projects'], ['tabs', 'Tabs'], ['stats', 'Insights'], ['settings', 'Settings']];
  useEffect(() => { const load = () => { void send('GET').then(setState).catch(e => setError(e.message)); }; load(); const unsub = subscribe(load); const tick = setInterval(() => setNow(Date.now()), 1000); return () => { unsub(); clearInterval(tick); }; }, []);
  useEffect(() => { document.documentElement.lang = 'en'; }, []);
  useEffect(() => { document.querySelector('nav [aria-current="page"]')?.scrollIntoView({ block: 'nearest', inline: 'nearest' }); }, [section]);
  useEffect(() => { if (state.taskDraft) { setEditor(state.taskDraft); setSection('tasks'); } }, [state.taskDraft?.title, state.taskDraft?.selectedText, state.taskDraft?.ambiguous?.messageId]);
  useEffect(() => { if (section === 'settings') { setSites(state.settings.excludedSites.join('\n')); setToken(state.settings.pairToken); } }, [section]);
  useEffect(() => { if (section === 'tabs') void send('LIST_TABS').then(setTabs).catch(e => setError(e.message)); }, [section]);
  useEffect(() => { if (!notice) return; const timeout = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timeout); }, [notice]);
  useEffect(() => {
    let current = true; setSiteAccess(null);
    if (isExtension && state.page?.url) {
      const origin = new URL(state.page.url).origin + '/*';
      void chrome.permissions.contains({ origins: [origin] }).then(allowed => { if (current) setSiteAccess(allowed); }).catch(() => {});
    }
    return () => { current = false; };
  }, [state.page?.url, granted]);
  async function allowSite() {
    try { const host = await grantCurrentSite(); setGranted(host); setSiteAccess(true); setNotice('Site access granted.'); await settings({}); }
    catch (e) { setError((e as Error).message); }
  }
  async function act(type: string, payload: Record<string, unknown> = {}) {
    if (type === 'SAVE_TASK') { const task = payload.task as Partial<Task> | undefined; if (task?.id) payload = { ...payload, expectedUpdatedAt: task.updatedAt ?? task.createdAt }; }
    setBusy(type); setError('');
    try { const result = await send(type, payload); setState(await send('GET')); if (['CLOSE_DUPLICATES', 'APPLY_GROUPS'].includes(type)) { setTabs(await send('LIST_TABS')); setSelected([]); } return result; }
    catch (e) { setError((e as Error).message); return undefined; }
    finally { setBusy(''); }
  }
  const settings = (value: object) => act('SETTINGS', { settings: value });
  const enableAI = async () => { if (await settings({ consent: true, aiMode: 'cloud' })) await act('CONNECT'); };
  const aiDisclosure = 'Your messages, selected text, task titles and page context go through Tabby Cloud to GPT Tunnel (DeepSeek). Visible page text is optional. You can turn AI off anytime.';
  function selectTask(id: string) { setTaskId(id); const task = state.tasks.find(t => t.id === id); if (task) setGoal(task.title); }
  function focusTask(task: Task) { setGoal(task.title); setTaskId(task.id); setSection('focus'); if (active) setEditGoal(true); }
  const assessment = state.assessment;
  const assessing = running && !s?.away && state.settings.consent && (!!state.pendingAt || state.ai.code === 'ANALYZING');
  const stateLabel = assessment?.category === 'aligned' ? 'On track' : assessment?.category === 'distracting' ? 'Possible distraction' : 'Not enough context';
  const waitingLabel = !state.settings.consent ? 'Analysis off' : !state.ai.connected ? 'AI not connected' : !running || s?.away ? 'Analysis paused' : 'Waiting for page context';
  const waitingReason = !state.ai.connected ? 'Enable the included AI in Settings for assessments.' : !running ? 'AI is connected. Press Resume to assess the current page.' : s?.away ? 'Analysis will resume when you return to the browser.' : 'Open an available page and stay there for about 8 seconds.';
  const taskCount = state.tasks.filter(x => x.status !== 'done').length;
  const totalFocus = [...state.history, ...(s ? [s] : [])].reduce((n, x) => n + x.totals.aligned + x.totals.distracting + x.totals.unknown, 0);
  const tabCandidates = tabs.filter(x => !x.active && !x.pinned && /^https?:/.test(x.url) && tabs.some(other => other.url === x.url && other.id !== x.id && (other.active || other.pinned || other.id < x.id)));
  const countDone = state.tasks.filter(x => x.status === 'done').length;
  return <div className={`app-shell ${isExtension ? 'extension' : 'preview'}`}>
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); setSection('mission'); }}><img className="tabby-logo" src={logo} alt="Tabby" width="125" height="36" /></a>
      <div className="sidebar-label">{'YOUR SPACE'}</div>
      <nav aria-label={'Sections'}>{nav.map(([id, label]) => { const Icon = icons[id]; return <button key={id} className={`nav-item ${section === id ? 'selected' : ''}`} onClick={() => setSection(id)} aria-current={section === id ? 'page' : undefined} title={label}><Icon size={19} /><span>{label}</span>{id === 'tasks' && taskCount > 0 && <small>{taskCount}</small>}{id === 'focus' && running && <i />}</button>; })}</nav>
      <div className="sidebar-bottom"><div className="little-plant" aria-hidden="true"><img src={sidebarCat} width="48" height="48" alt="" /><span>✳</span></div><h3>{'One thing at a time.'}</h3><p>{'Make a little room for what matters.'}</p><div className="local-note"><ShieldCheck size={14} />{'Your data · your control'}</div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><span className="breadcrumb">{'My workspace'}<ChevronRight size={13} /><strong>{nav.find(n => n[0] === section)?.[1]}</strong></span><div className="topbar-actions"><button className={`connection-dot ${state.ai.connected ? 'online' : ''}`} onClick={() => setSection('settings')}><i />{!state.settings.consent ? 'AI included · enable' : state.ai.connected ? state.ai.model : 'Check AI connection'}</button></div></header>
      <main>
        {!isExtension && <div className="preview-note"><span><Focus size={15} />{'Web preview'}</span>{'Timer and tasks are saved here. Install the extension to analyze pages and manage browser tabs.'}</div>}
        {error && <div role="alert" className="alert error"><span>{errorText(error)}</span><button className="icon-button" onClick={() => setError('')} aria-label={'Dismiss'}><X size={16} /></button></div>}
        {notice && <div role="status" className="alert success"><Check size={16} />{notice}</div>}
        {(section === 'mission' || section === 'focus') && isExtension && !state.settings.consent && <section className="card ai-welcome"><div className="kicker"><Sparkles size={16} />AI INCLUDED</div><h2>Your sidekick is ready.</h2><p>No account, API key or local server needed.</p><p className="ai-disclosure">{aiDisclosure}</p><button className="btn primary" disabled={!!busy} onClick={enableAI}><Sparkles size={16} />Enable AI</button></section>}
        {section === 'mission' && <MissionView state={state} session={s} busy={busy} enabled={isExtension} act={act} onFocus={() => setSection('focus')} />}
        {section === 'focus' && <>
          <div className="page-heading"><div><div className="eyebrow"><span />{'LESS NOISE. MORE INTENTION.'}</div><h1>{active ? 'A little room to focus.' : 'What matters today?'}</h1><p>{'One task, a little attention. You’re on your way.'}</p></div><span className="heading-spark" aria-hidden="true">✳</span></div>
          <div className="focus-layout"><div className="focus-main">
            <section className="card timer-card">
              <div className="card-top"><span className="kicker"><Focus size={15} />{'FOCUS SESSION'}</span><span className={`pill ${running ? 'green' : ''}`}>{s?.away && running ? 'Away' : s?.phase === 'break' ? 'On a break' : s?.phase === 'paused' ? 'Paused' : s?.phase === 'ready' ? 'Ready to return' : running ? 'In progress' : s?.phase === 'finished' ? 'Finished' : 'Your pace'}</span></div>
              <div className="timer-garden"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="orbit-leaf"><img src={cat} width="32" height="32" alt="" /></span><span className="orbit-star">✧</span><div className="timer-center"><span className="timer-caption">{s?.phase === 'break' ? 'A MOMENT TO BREATHE' : 'TIME FOR WHAT MATTERS'}</span><div className="timer-digits" role="timer" aria-label={'Time remaining'}>{time(s?.phase === 'break' ? (s.breakUntil || now) - now : active ? s!.remainingMs : duration * 60000)}</div><span className="timer-whisper">{running ? 'No rush. You’re here.' : 'A small step is still a step.'}</span></div></div>
              {(!active || editGoal) ? <form className="goal-form" onSubmit={async e => { e.preventDefault(); const result = await act(active ? 'GOAL' : 'START', { goal, taskId, minutes: duration }); if (result) setEditGoal(false); }}>
                <label htmlFor="goal">{'What would you like to focus on?'}</label><textarea id="goal" required maxLength={1000} value={goal} onChange={e => setGoal(e.target.value)} placeholder={'For example, learn React authentication and build an example'} rows={2} />
                <select aria-label={'Active task'} value={taskId} onChange={e => selectTask(e.target.value)}><option value="">{'Custom goal · no task'}</option>{state.tasks.filter(t => t.status !== 'done').map(task => <option key={task.id} value={task.id}>{task.title}</option>)}</select>
                {!active && <div className="duration-row"><span>{'Minutes'}</span><div className="segmented">{[25, 50].map(m => <button key={m} type="button" className={duration === m ? 'on' : ''} onClick={() => setDuration(m)}>{m}</button>)}<input aria-label={'Custom duration in minutes'} type="number" min={1} max={480} value={duration} onChange={e => setDuration(Number(e.target.value))} /></div></div>}
                <button type="submit" className="btn primary full" disabled={!!busy || !goal.trim()}>{busy === 'START' ? <LoaderCircle className="spin" size={17} /> : <Play size={16} fill="currentColor" />}{active ? 'Update goal' : 'Start focusing'}<span className="button-end">↗</span></button>
                {editGoal && <button type="button" className="text-button" onClick={() => setEditGoal(false)}>{'Cancel'}</button>}
              </form> : <div className="active-controls"><div className="active-goal"><Target size={19} /><div><span>{'YOUR GOAL'}</span><h2>{s?.goal}</h2></div><button className="icon-button" aria-label={'Edit goal'} onClick={() => { setGoal(s!.goal); setTaskId(s!.taskId); setEditGoal(true); }}><Pencil size={16} /></button></div><div className="compact-assessment"><span className={`pill ${assessment?.category === 'aligned' ? 'green' : ''}`}>{assessing ? 'Assessing this page…' : assessment ? stateLabel : waitingLabel}</span><p>{assessment?.nextStep || 'The timer follows your pace. The next step is yours.'}</p>{assessment?.category === 'distracting' && <button className="text-button" onClick={() => act('RETURN')}>{'Back to work'}<ArrowRight size={13} /></button>}</div><div className="button-row"><button className="btn primary" onClick={() => act(running ? 'PAUSE' : 'RESUME')}>{running ? <Pause size={16} /> : <Play size={16} />}{running ? 'Pause' : 'Resume'}</button>{s?.phase !== 'break' && <button className="btn secondary" onClick={() => act('BREAK', { minutes: state.settings.breakMinutes })}><Coffee size={16} />{'Break'} · {state.settings.breakMinutes}{'m'}</button>}</div></div>}
              <div className="timer-footer"><ShieldCheck size={13} />{active ? 'Session saved. You can close this panel.' : 'Observation starts only when you start a session.'}</div>
            </section>
            {s?.resumeCard && <section className="card resume-card"><div className="kicker"><RotateCcw size={16} />{'PICK UP WHERE YOU LEFT OFF'}</div><h2>{s.goal}</h2><p className="small-label">{'Saved facts'}</p><p>{s.lastConfirmedStep ? `${'Your last confirmed step:'} ${s.lastConfirmedStep}` : 'No last step has been confirmed.'}</p>{s.workTabs.length > 0 && <ul className="resource-list">{s.workTabs.map(tab => <li key={tab.tabId}><FileText size={14} />{tab.title}</li>)}</ul>}<p className="muted">{'An open tab does not mean its contents were read.'}</p><button className="btn primary" onClick={() => act('RETURN')}><ArrowRight size={16} />{'Back to work tabs'}</button><button className="text-button" onClick={() => act('AI', { kind: 'next' })}>{'Suggest the next step'}</button></section>}
            <div className="gentle-note"><span>✳</span><p>{'Attention is a practice, not a perfect score.'}<small>{'It’s okay to wander. You can always return.'}</small></p></div>
          </div><div className="focus-aside">
            <section className={`card context-card ${assessment?.category || ''}`}><div className="card-top"><span className="kicker"><Sparkles size={15} />{'ALONGSIDE YOUR FOCUS'}</span><span className="tiny-dot" /></div>
              <div className="context-symbol">{assessment?.category === 'aligned' ? <Check size={25} /> : assessment?.category === 'distracting' ? <Leaf size={25} /> : <Sparkles size={25} />}</div>
              <h2>{assessing ? 'Finding the context…' : !active ? 'Your goal comes first.' : !state.settings.consent ? 'Analysis is off' : assessment ? stateLabel : waitingLabel}</h2>
              <p>{assessing && state.pendingAt ? 'Giving this page about 8 seconds. A passing tab isn’t a distraction.' : assessment?.reason || (!active ? 'Start a session to see context about your current page and a gentle suggestion.' : !state.settings.consent ? 'You decide when to share page context with AI.' : waitingReason)}</p>
              {state.page && <div className="page-source"><span><FileText size={14} />{state.page.title || 'Untitled'}</span><small>{new URL(state.page.url).hostname}</small></div>}
              {state.page && siteAccess === false && <div><p className="muted">Page text and in-page reminders need permission for this site.</p><button className="text-button" onClick={allowSite}><Plus size={14} />Allow access to this site</button></div>}
              {assessment?.nextStep && <div className="next-step"><span>{'SUGGESTION'}</span><p>{assessment.nextStep}</p><button className="text-button" onClick={() => act('CONFIRM_STEP', { step: assessment.nextStep })}><CheckCheck size={14} />{'I completed this step'}</button></div>}
              {running && state.page && <div className="context-actions">{assessment?.category === 'distracting' && <button className="btn primary full" onClick={() => act('RETURN')}><ArrowRight size={16} />{'Back to work'}</button>}<div className="button-row"><button className="btn secondary" onClick={() => act('CORRECT')}><Check size={15} />{'This is relevant'}</button><button className="btn secondary" onClick={() => act('BREAK', { minutes: 5 })}><Coffee size={15} />5 {'minutes'}</button></div><button className="text-button" disabled={!!busy} onClick={() => act('AI', { kind: 'next' })}><Sparkles size={14} />{busy === 'AI' ? 'Thinking…' : 'Help me continue'}</button></div>}
              {state.settings.consent && !state.ai.connected && <button className="text-button" disabled={!!busy} onClick={() => act('CONNECT')}>Retry connection<ArrowUpRight size={15} /></button>}
              {assessment?.source === 'user' && <span className="user-confirmed"><CheckCheck size={12} />{'Your correction · this context only'}</span>}
            </section>
            <section className="card up-next"><div className="card-top"><span className="kicker"><ListTodo size={15} />{'WITHIN REACH'}</span><button className="icon-button" aria-label={'Add task'} onClick={() => { setEditor({}); setSection('tasks'); }}><Plus size={17} /></button></div>{state.tasks.filter(x => x.status !== 'done').slice(0, 3).map(task => <button className="mini-task" key={task.id} onClick={() => focusTask(task)}><span className="task-circle" /><span>{task.title}</span><ArrowUpRight size={14} /></button>)}{!taskCount && <div className="small-empty"><p>{'Free up some headspace.'}</p><span>{'Write down your first task so you don’t have to keep it in mind.'}</span><button className="text-button" onClick={() => { setEditor({}); setSection('tasks'); }}><Plus size={14} />{'Add a task'}</button></div>}</section>
            <section className="today-card"><div><span>{'SESSION TIME'}</span><strong>{minutes(totalFocus)} <small>{'min'}</small></strong></div><div className="today-divider" /><div><span>{'TASKS DONE'}</span><strong>{countDone}<small> <CheckCheck size={17} /></small></strong></div><p>{'Real events. No productivity score.'}</p></section>
          </div></div>
        </>}
        {section === 'ambiguous' && <AmbiguousView state={state} act={act} busy={!!busy} />}
        {section === 'projects' && <ProjectsView state={state} selected={projectId} setSelected={setProjectId} act={act} busy={!!busy} onTask={task => { setEditor(task); setSection('tasks'); }} onFocus={focusTask} />}
        {section === 'tasks' && <><PageHeading title={'A little less on your mind.'} description={'Keep your tasks here. Pick one to focus on.'} kicker={'YOUR TASKS'} /><div className="section-toolbar"><span>{taskCount} {'to go'} · {countDone} {'done'}</span><div className="button-row"><button className="btn secondary" disabled={!!busy} onClick={() => act('AI', { kind: 'task' })}><Sparkles size={16} />{'From page'}</button><button className="btn primary" onClick={() => setEditor({})}><Plus size={16} />{'New task'}</button></div></div>
          {editor && <TaskEditor key={editor.id || editor.title || 'new'} task={editor} projects={state.projects} busy={!!busy} onClose={() => { setEditor(null); void act('CLEAR_DRAFT'); }} onAI={state.taskDraft?.selectedText ? () => { void act('AI', { kind: 'task' }); } : undefined} onSave={async task => { if (await act('SAVE_TASK', { task })) setEditor(null); }} />}
          {!state.tasks.length && !editor && <Empty icon={<ListTodo size={35} />} title={'A first step starts with a note.'} text={'Add a task, or select text on a page and choose Tabby in Chrome’s context menu.'} />}
          <div className="task-list">{state.tasks.map(task => <article className={`card task-row ${task.status === 'done' ? 'done' : ''}`} key={task.id}><button className={`check-button ${task.status === 'done' ? 'checked' : ''}`} aria-label={task.status === 'done' ? 'Mark as planned' : 'Mark done'} onClick={() => act('SAVE_TASK', { task: { ...task, status: task.status === 'done' ? 'planned' : 'done' } })}>{task.status === 'done' && <Check size={15} />}</button><div className="task-detail"><h3>{task.title}</h3><div className="task-meta"><span className={`pill ${task.status === 'doing' ? 'green' : ''}`}>{task.status === 'doing' ? 'In progress' : task.status === 'done' ? 'Done' : 'Planned'}</span>{task.due && <span>{task.due}</span>}{task.source && <a href={task.source} target="_blank" rel="noreferrer"><ExternalLink size={12} />{'Source'}</a>}</div>{task.steps.length > 0 && <ol>{task.steps.map((step, i) => <li key={i}>{step}</li>)}</ol>}</div><div className="task-actions"><button className="icon-button" title={'Edit'} aria-label={'Edit'} onClick={() => setEditor(task)}><Pencil size={16} /></button>{task.status !== 'done' && <button className="icon-button" title={'Focus on this'} aria-label={'Focus on this'} onClick={() => focusTask(task)}><Focus size={18} /></button>}</div></article>)}</div>
        </>}
        {section === 'tabs' && <><PageHeading title={'A home for every thought.'} description={'Tabs in this window. Grouping always starts with your review.'} kicker={'YOUR BROWSER'} /><div className="section-toolbar"><input className="search-input" type="search" aria-label={'Search tabs'} placeholder={'Find a tab…'} value={search} onChange={e => setSearch(e.target.value)} /><button className="btn secondary" onClick={async () => setTabs(await send('LIST_TABS'))}><RotateCcw size={15} />{'Refresh'}</button></div><div className="button-row tab-tools"><button className="btn primary" disabled={!!busy || !tabs.length} onClick={() => act('AI', { kind: 'groups' })}><Sparkles size={16} />{'Suggest groups'}</button><span className="muted">{tabs.length} {'tabs'} · {tabCandidates.length} {'exact duplicates'}</span></div>
          {state.groupDraft && <section className="card group-review"><div className="kicker">{'AI SUGGESTION · REVIEW MEMBERS'}</div>{state.groupDraft.map((g, i) => <div className="group-item" key={i}><h3><i style={{ background: g.color }} />{g.title}</h3><ul>{g.tabIds.map(id => <li key={id}>{tabs.find(t => t.id === id)?.title || `#${id}`}</li>)}</ul></div>)}<button className="btn primary" disabled={!!busy} onClick={() => act('APPLY_GROUPS')}><Layers size={16} />{'Confirm & create groups'}</button></section>}
          {!tabs.length && <Empty icon={<Layers size={35} />} title={'Your tabs will feel at home here.'} text={isExtension ? 'Open a page in this window and refresh.' : 'The web preview cannot access your tabs. Install the Chrome extension.'} />}
          <div className="tab-list">{tabs.filter(tab => (tab.title + tab.url).toLowerCase().includes(search.toLowerCase())).map(tab => <article className="card tab-row" key={tab.id}>{tabCandidates.some(t => t.id === tab.id) ? <input type="checkbox" aria-label={'Select duplicate: ' + tab.title} checked={selected.includes(tab.id)} onChange={e => setSelected(e.target.checked ? [...selected, tab.id] : selected.filter(id => id !== tab.id))} /> : <span className="tab-icon"><FileText size={18} /></span>}<button className="tab-title" onClick={() => act('ACTIVATE_TAB', { tabId: tab.id })}><strong>{tab.title}</strong><small>{tab.url ? (() => { try { return new URL(tab.url).hostname || tab.url; } catch { return ''; } })() : ''}</small></button>{tab.active && <span className="pill green">{'Active'}</span>}{tabCandidates.some(t => t.id === tab.id) && <Copy size={15} className="muted" />}</article>)}</div>
          {selected.length > 0 && <section className="card duplicate-review"><p>{'Selected duplicates:'} {selected.length}. {'Selected tabs may contain unsaved data.'}</p>{confirmDuplicates ? <><ul>{tabs.filter(t => selected.includes(t.id)).map(t => <li key={t.id}>{t.title}</li>)}</ul><div className="button-row"><button className="btn danger" onClick={async () => { await act('CLOSE_DUPLICATES', { tabIds: selected }); setConfirmDuplicates(false); }}>{'Close selected tabs'}</button><button className="btn secondary" onClick={() => setConfirmDuplicates(false)}>{'Cancel'}</button></div></> : <button className="btn secondary" onClick={() => setConfirmDuplicates(true)}><Trash2 size={15} />{'Review before closing'}</button>}</section>}
        </>}
        {section === 'stats' && <><PageHeading title={'Notice your own rhythm.'} description={'Observations from your sessions. Time on a site isn’t proof of productivity.'} kicker={'YOUR INSIGHTS'} /><AdvancedInsights state={state} />{!s && !state.history.length ? <Empty icon={<BarChart3 size={35} />} title={'It starts with your first session.'} text={'Real time intervals and your confirmed outcomes will appear here.'} /> : <><div className="stats-grid"><Stat label={'Session time'} value={`${minutes(totalFocus)} ${'min'}`} /><Stat label={'Breaks'} value={`${minutes([...state.history, ...(s ? [s] : [])].reduce((n, x) => n + x.totals.break, 0))} ${'min'}`} /><Stat label={'Tasks marked done'} value={String(countDone)} /></div>{[...(s ? [s] : []), ...state.history].map(session => { const work = session.totals.aligned + session.totals.distracting + session.totals.unknown; return <section className="card session-report" key={session.id}><div className="card-top"><span className="kicker">{new Date(session.startedAt).toLocaleDateString('en-US', { day: 'numeric', month: 'long' })}</span><span className="pill">{session.phase === 'finished' ? 'Finished' : 'Current session'}</span></div><h2>{session.goal}</h2><div className="distribution" aria-label={'Time distribution'}>{(['aligned', 'distracting', 'unknown'] as const).map(c => <span key={c} className={c} style={{ width: `${work ? session.totals[c] / work * 100 : 0}%` }} />)}</div><div className="time-legend">{(['aligned', 'distracting', 'unknown', 'break', 'away', 'paused'] as const).map((c, i) => <div key={c}><span><i className={c} />{['On track', 'Possible distraction', 'Unclassified', 'Break', 'Away', 'Paused / waiting'][i]}</span><strong>{time(session.totals[c])}</strong></div>)}</div><div className="report-counts"><span>{session.reminders} {'reminders'}</span><span>{session.returns} {'returns to work'}</span></div>{session.summary && <div className="summary"><h3>{'Facts from events'}</h3><ul>{session.summary.facts.map((f, i) => <li key={i}>{f}</li>)}</ul><h3>{'AI suggestions'}</h3><ul>{session.summary.suggestions.map((f, i) => <li key={i}>{f}</li>)}</ul></div>}{session.phase === 'finished' && session.ambiguous && !session.ambiguousReport && <button className="text-button" disabled={!!busy || !state.ambiguous.enabled} onClick={async () => { if (await act('AMBIGUOUS_PREPARE_REPORT', { sessionId: session.id })) setSection('ambiguous'); }}>Share to Ambiguous<ArrowUpRight size={15} /></button>}{session.id === s?.id && <button className="text-button" disabled={!!busy} onClick={() => act('AI', { kind: 'summary' })}><Sparkles size={15} />{'Get an AI recap'}</button>}</section>; })}</>}
          <section className="card usage-card"><div className="kicker"><Sparkles size={15} />{'AI USAGE'}</div><div className="usage-values"><div><span>{'Tokens'}</span><strong>{state.usage.total_tokens ?? '—'}</strong></div><div><span>{'Cost reported by provider'}</span><strong>{state.usage.total_cost !== undefined ? `${state.usage.total_cost.toFixed(5)}` : '—'}</strong></div></div><p className="muted">{'Only data returned by the server is shown. An empty field does not mean zero cost.'}</p></section>
        </>}
        {section === 'settings' && <><PageHeading title={'Your focus. Your rules.'} description={'You stay in control of your data and your assistance.'} kicker={'SETTINGS'} /><div className="settings-grid">
          <section className="card settings-card ai-welcome"><div className="kicker"><Sparkles size={16} />AI INCLUDED</div><h2>One click. A little more clarity.</h2><p>DeepSeek is included in the hackathon preview. No account, key or local server needed. Fair-use limits apply.</p><p className="ai-disclosure">{aiDisclosure}</p>{!state.settings.consent || state.settings.aiMode === 'local' ? <button className="btn primary" disabled={!!busy || !isExtension} onClick={enableAI}><Sparkles size={16} />{state.settings.aiMode === 'local' ? 'Use included AI' : 'Enable AI'}</button> : <div className="button-row"><span className={state.ai.connected ? 'success-text' : 'muted'}>{state.ai.connected ? 'DeepSeek is connected.' : 'Ready to connect to Tabby Cloud.'}</span><button className="btn secondary" disabled={!!busy} onClick={() => act('CONNECT')}>{busy === 'CONNECT' ? <LoaderCircle size={16} className="spin" /> : <RotateCcw size={16} />}Check connection</button></div>}</section>
          <section className="card settings-card privacy-card"><div className="kicker"><ShieldCheck size={16} />{'DATA & PERMISSIONS'}</div><h2>{'Just enough context.'}</h2><p>{'Analysis sends your goal, selected task, page title, cleaned URL, time on page, recent session events and corrections through Tabby Cloud (or your selected local companion) to GPT Tunnel and the model. Grouping sends titles and cleaned URLs from this window; extraction sends selected text.'}</p><Toggle label={'Allow AI analysis'} hint={'Observation only during a running session. Tasks and grouping only on request.'} checked={state.settings.consent} onChange={async v => { if (await settings({ consent: v }) && v) await act('CONNECT'); }} /><Toggle label={'Include visible page text'} hint={'Up to 4,000 characters, excluding forms and inputs. Requires site permission.'} checked={state.settings.readText} onChange={v => settings({ readText: v })} /><button className="btn secondary" onClick={async () => { try { const host = await grantCurrentSite(); setGranted(host); setNotice('Site access granted.'); if (isExtension) await settings({}); } catch (e) { setError((e as Error).message); } }}><Plus size={15} />{'Allow access to current site'}</button>{granted && <p className="success-text">{granted}</p>}<label htmlFor="excluded-sites">{'Excluded sites'}</label><textarea id="excluded-sites" rows={3} value={sites} onChange={e => setSites(e.target.value)} placeholder="bank.example.com" /><p className="small-label">{'One domain per line. Subdomains are excluded too.'}</p><button className="text-button" onClick={async () => { await settings({ excludedSites: normalizeSites(sites) }); setNotice('Exclusions saved.'); }}><Check size={15} />{'Save exclusions'}</button></section>
          <section className="card settings-card"><div className="kicker"><Leaf size={16} />{'HOW WE CAN HELP'}</div><div className="mode-options">{(['soft', 'strict'] as const).map(mode => <button key={mode} className={`mode-option ${state.settings.mode === mode ? 'chosen' : ''}`} onClick={() => settings({ mode })}><span>{mode === 'soft' ? <Leaf size={19} /> : <ShieldCheck size={19} />}<strong>{mode === 'soft' ? 'Gentle' : 'Strict'}</strong><span className="radio-dot" /></span><p>{mode === 'soft' ? 'Gentle reminders and an invitation to return.' : 'A temporary cover over a distracting page. Correct it, take a break or stop anytime.'}</p></button>)}</div>{state.settings.mode === 'strict' && <p className="small-label">{'Grant site access above for the cover. It clears if AI is unavailable; connection checks every 30 seconds, with a 40-second lease.'}</p>}<label htmlFor="break-minutes">{'Default break length, minutes'}</label><input id="break-minutes" type="number" min={1} max={120} value={state.settings.breakMinutes} onChange={e => settings({ breakMinutes: Number(e.target.value) })} /></section>
          <section className="card settings-card"><div className="kicker"><FileText size={16} />{'LAST CONFIRMED STEP'}</div><p>{'Write down what you actually completed. It helps you pick up after a break.'}</p><textarea aria-label={'Confirmed step'} rows={2} value={step} maxLength={600} onChange={e => setStep(e.target.value)} placeholder={s?.lastConfirmedStep || 'For example: created a login form component'} /><button className="text-button" disabled={!s || !step.trim()} onClick={async () => { await act('CONFIRM_STEP', { step }); setNotice('Your step is saved.'); }}><CheckCheck size={15} />{'Confirm step'}</button><hr /><p>{'Sessions, tasks and corrections are stored locally. Clearing removes them and the extension connection token.'}</p>{confirmClear ? <div className="button-row"><button className="btn danger" onClick={async () => { await act('CLEAR_DATA'); setConfirmClear(false); setSection('focus'); }}>{'Delete local data'}</button><button className="btn secondary" onClick={() => setConfirmClear(false)}>{'Cancel'}</button></div> : <button className="text-button danger-text" onClick={() => setConfirmClear(true)}><Trash2 size={14} />{'Clear local data'}</button>}</section>
          <details className="advanced-settings"><summary>Connected tools &amp; advanced settings</summary><p className="muted">Optional. The included AI works without any of these connections.</p><WorkspaceSettings state={state} act={act} busy={!!busy} /><section className="card settings-card"><div className="kicker"><LockKeyhole size={16} />LOCAL COMPANION</div><h2>Bring your own setup.</h2><p>Only for a local AI provider or connected Google and Ambiguous accounts. Run the companion and use the token from .local/pairing.txt.</p><label htmlFor="pair-token">Local server connection token</label><input id="pair-token" type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} placeholder="Not the GPT Tunnel API key" /><div className="button-row"><button className="btn secondary" disabled={!!busy} onClick={() => settings({ pairToken: token, aiMode: state.settings.aiMode })}>Save companion token</button><button className="btn secondary" disabled={!!busy || !token} onClick={async () => { if (await settings({ pairToken: token, aiMode: 'local' })) await act('CONNECT'); }}>Use local AI</button></div><p className="small-label">Current AI: {state.settings.aiMode === 'local' ? 'Local companion' : 'Included Tabby Cloud'}</p></section></details>
        </div></>}
        {section === 'google' && <GooglePanel state={state} busy={!!busy} command={act} openSettings={() => setSection('settings')} openTasks={() => setSection('tasks')} openChat={() => setSection('chat')} />}
        {section === 'chat' && <ChatPanel state={state} busy={!!busy} command={act} openSettings={() => setSection('settings')} enableAI={enableAI} />}
        <footer className="page-footer"><span><img src={cat} width="16" height="16" alt="" />Tabby</span><span>{'Fewer open loops.'} <Leaf size={12} /></span></footer>
      </main>
      {active && !(section === 'mission' && state.missions.current && s!.missionId === state.missions.current.id) && <div className="session-dock"><span><i className={running ? 'pulsing' : ''} /><strong>{time(s!.phase === 'break' ? (s!.breakUntil || now) - now : s!.remainingMs)}</strong><span>{s!.goal}</span></span><button onClick={() => act('STOP')}><Square size={13} />{'Stop session'}</button></div>}
    </div>
  </div>;
}
function PageHeading({ title, description, kicker }: { title: string; description: string; kicker: string }) { return <div className="page-heading"><div><div className="eyebrow"><span />{kicker}</div><h1>{title}</h1><p>{description}</p></div><span className="heading-spark" aria-hidden="true">✳</span></div>; }
function Empty({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <div className="empty-state"><div>{icon}</div><h2>{title}</h2><p>{text}</p></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="card stat"><span>{label}</span><strong>{value}</strong></div>; }
function Toggle({ label, hint, checked, onChange }: { label: string; hint: string; checked: boolean; onChange: (v: boolean) => void }) { return <label className="toggle-row"><span><strong>{label}</strong><small>{hint}</small></span><input role="switch" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /></label>; }
function TaskEditor({ task, projects, busy, onSave, onClose, onAI }: { task: Partial<Task>; projects: AppState['projects']; busy: boolean; onSave: (task: Partial<Task>) => void; onClose: () => void; onAI?: () => void }) {
  const [projectId, setProjectId] = useState(task.projectId || '');
  const [title, setTitle] = useState(task.title || ''); const [steps, setSteps] = useState(task.steps?.join('\n') || ''); const [due, setDue] = useState(task.due || ''); const [source, setSource] = useState(task.source || ''); const [status, setStatus] = useState(task.status || 'planned');
  function submit(e: FormEvent) { e.preventDefault(); onSave({ ...task, projectId, title, steps: steps.split('\n').map(x => x.trim()).filter(Boolean).slice(0, 8), source, due, status }); }
  return <form className="card task-editor" onSubmit={submit}><div className="card-top"><h2>{task.id ? 'Refine your task' : 'A new task'}</h2><button className="icon-button" type="button" onClick={onClose} aria-label={'Close editor'}><X size={18} /></button></div><p className="muted">{'Review the title and steps before saving.'}</p>{task.ambiguous && <p className="small-label">From Ambiguous · #{task.ambiguous.channelName}. Session reports can reply to the original thread.</p>}<label htmlFor="task-title">{'Title'}</label><input id="task-title" autoFocus required maxLength={180} value={title} onChange={e => setTitle(e.target.value)} /><label htmlFor="task-steps">{'Short steps · one per line'}</label><textarea id="task-steps" rows={3} value={steps} onChange={e => setSteps(e.target.value)} /><div className="form-columns"><div><label htmlFor="task-status">{'Status'}</label><select id="task-status" value={status} onChange={e => setStatus(e.target.value as Task['status'])}><option value="planned">{'Planned'}</option><option value="doing">{'In progress'}</option><option value="done">{'Done'}</option></select></div><div><label htmlFor="task-due">{'Due date · optional'}</label><input id="task-due" type="date" value={due} onChange={e => setDue(e.target.value)} /></div></div><label htmlFor="task-project">Project</label><select id="task-project" value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">No project</option>{projects.filter(p => !p.archived || p.id === task.projectId).map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select><label htmlFor="task-source">{'Source link'}</label><input id="task-source" type="url" value={source} onChange={e => setSource(e.target.value)} placeholder="https://…" /><div className="button-row"><button className="btn primary" type="submit" disabled={busy || !title.trim()}><Check size={16} />{'Save task'}</button>{onAI && <button className="btn secondary" type="button" disabled={busy} onClick={onAI}><Sparkles size={15} />{'Refine with AI'}</button>}</div></form>;
}
createRoot(document.getElementById('root')!).render(<App />);
