import { useEffect, useState, type FormEvent } from 'react';
import { Archive, Check, FileText, Folder, Plus, Trash2, X, ExternalLink, Pencil } from 'lucide-react';
import type { AppState, Project, Note, Task } from '../shared/types';
import { send, isExtension } from './bridge';
import { analytics } from '../shared/analytics';
import { errorText } from './errors';
type Act = (type: string, payload?: Record<string, unknown>) => Promise<any>;
export function ProjectsView({ state, selected, setSelected, act, busy, onTask, onFocus }: { state: AppState; selected: string; setSelected: (id: string) => void; act: Act; busy: boolean; onTask: (task: Partial<Task>) => void; onFocus: (task: Task) => void }) {
  const [showArchived, setShowArchived] = useState(false);
  const [editor, setEditor] = useState<Partial<Project> | null>(null); const [note, setNote] = useState<Partial<Note> | null>(null);
  const [tabs, setTabs] = useState<Array<{ id: number; title: string; url: string }>>([]); const [tabId, setTabId] = useState('');
  const [error, setError] = useState(''); const [confirmDelete, setConfirmDelete] = useState<{ id: string; updatedAt: number } | null>(null);
  const projects = state.projects.filter(p => showArchived || !p.archived);
  const project = state.projects.find(p => p.id === selected);
  useEffect(() => { if (isExtension && selected) void send('LIST_TABS').then(setTabs).catch(e => setError(e.message)); }, [selected]);
  const pins = state.pinnedTabs.filter(p => p.projectId === selected && !p.deletedAt);
  const notes = state.notes.filter(n => n.projectId === selected && !n.deletedAt);
  const tasks = state.tasks.filter(t => t.projectId === selected);
  return <>
    <div className="page-heading"><div><div className="eyebrow"><span />YOUR PROJECTS</div><h1>Keep the pieces together.</h1><p>A home for your tasks, useful tabs and notes.</p></div></div>
    <div className="section-toolbar"><label className="inline-check"><input type="checkbox" checked={showArchived} onChange={e => setShowArchived(e.target.checked)} />Show archived</label><button className="btn primary" onClick={() => setEditor({})}><Plus size={16} />New project</button></div>
    {error && <p role="alert">{errorText(error)}</p>}
    {editor && <ProjectEditor key={`${editor.id || 'new'}:${editor.updatedAt || ''}`} value={editor} busy={busy} close={() => setEditor(null)} save={async value => { const result = await act('SAVE_PROJECT', { project: value, expectedUpdatedAt: editor.updatedAt }); if (result) { setSelected(value.id || result.projects[0].id); setEditor(null); } }} />}
    {!state.projects.length && !editor && <section className="card project-empty"><Folder size={32} /><h2>Your next idea starts here.</h2><p>Create a project, then add a task or save a useful tab.</p></section>}
    {!!projects.length && <label className="project-picker">Project<select aria-label="Selected project" value={selected} onChange={e => { setSelected(e.target.value); setNote(null); setConfirmDelete(null); }}><option value="">Choose a project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.title}{p.archived ? ' · Archived' : ''}</option>)}</select></label>}
    {project && <>
      <section className="card project-overview"><div className="card-top"><h2>{project.title}</h2><button className="icon-button" aria-label="Edit project" onClick={() => setEditor(project)}><Pencil size={16} /></button></div><p className="preserve-lines">{project.description}</p><div className="report-counts"><span>{tasks.filter(t => t.status !== 'done').length} open tasks</span><span>{pins.length} saved tabs</span><span>{notes.length} notes</span></div><button className="text-button" disabled={busy} onClick={() => act('SAVE_PROJECT', { project: { id: project.id, title: project.title, description: project.description, archived: !project.archived }, expectedUpdatedAt: project.updatedAt })}><Archive size={14} />{project.archived ? 'Restore project' : 'Archive project'}</button></section>
      <section className="card project-section"><div className="card-top"><h2>Tasks</h2><button className="text-button" disabled={project.archived} onClick={() => onTask({ projectId: project.id })}><Plus size={14} />Add task</button></div>{tasks.map(t => <div className="project-task" key={t.id}><button className="icon-button" aria-label={(t.status === 'done' ? 'Reopen ' : 'Complete ') + t.title} disabled={busy} onClick={() => act('SAVE_TASK', { task: { ...t, status: t.status === 'done' ? 'planned' : 'done' } })}>{t.status === 'done' ? <Check size={18} /> : <span className="task-circle" />}</button><button className="tab-title" onClick={() => onTask(t)}><strong>{t.title}</strong><small>{t.status === 'done' ? 'Done' : t.due || 'No due date'}</small></button>{t.status !== 'done' && <button className="text-button" onClick={() => onFocus(t)}>Focus</button>}</div>)}{!tasks.length && <p className="muted">Choose one small next step.</p>}</section>
      <section className="card project-section"><h2>Pinned tabs</h2><p className="muted">Saved links stay with this project after a tab closes. Search terms and tracking parameters are removed.</p>{isExtension && !project.archived && <div className="pin-controls"><select aria-label="Tab to pin" value={tabId} onChange={e => setTabId(e.target.value)}><option value="">Choose an open tab</option>{tabs.filter(t => /^https?:/.test(t.url)).map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select><button className="btn secondary" disabled={busy || !tabId} onClick={() => act('PIN_TAB', { projectId: project.id, tabId: Number(tabId) })}>Pin tab</button><button className="text-button" onClick={() => { void send('LIST_TABS').then(setTabs).catch(e => setError(e.message)); }}>Refresh</button></div>}{!isExtension && <p className="muted">Install Tabby to pin browser tabs.</p>}{pins.map(pin => <div className="project-task" key={pin.id}><FileText size={18} /><button className="tab-title" onClick={() => act('OPEN_PIN', { id: pin.id })}><strong>{pin.title}</strong><small>{pin.url}</small></button><ExternalLink size={14} /><button className="icon-button" aria-label={'Unpin ' + pin.title} onClick={() => act('UNPIN_TAB', { id: pin.id, expectedUpdatedAt: pin.updatedAt })}><X size={15} /></button></div>)}</section>
      <section className="card project-section"><div className="card-top"><h2>Notes</h2><button className="text-button" disabled={project.archived} onClick={() => setNote({ projectId: project.id })}><Plus size={14} />New note</button></div>{note && <NoteEditor key={`${note.id || 'new'}:${note.updatedAt || ''}`} value={note} busy={busy} close={() => setNote(null)} save={async value => { if (await act('SAVE_NOTE', { note: value, expectedUpdatedAt: note.updatedAt })) setNote(null); }} />}{notes.map(n => <article className="project-note" key={n.id}><div className="card-top"><h3>{n.title}</h3><div className="button-row"><button className="icon-button" aria-label={'Edit note ' + n.title} disabled={project.archived} onClick={() => setNote(n)}><Pencil size={15} /></button><button className="icon-button" aria-label={'Delete note ' + n.title} onClick={() => setConfirmDelete({ id: n.id, updatedAt: n.updatedAt })}><Trash2 size={15} /></button></div></div><p className="preserve-lines">{n.body}</p>{confirmDelete?.id === n.id && <div className="button-row"><button className="btn danger" disabled={busy} onClick={async () => { if (await act('DELETE_NOTE', { id: n.id, expectedUpdatedAt: confirmDelete.updatedAt })) setConfirmDelete(null); }}>Delete note</button><button className="btn secondary" onClick={() => setConfirmDelete(null)}>Cancel</button></div>}</article>)}</section>
    </>}
  </>;
}
function ProjectEditor({ value, busy, save, close }: { value: Partial<Project>; busy: boolean; save: (v: { id?: string; title: string; description: string; archived: boolean }) => void; close: () => void }) {
  const [title, setTitle] = useState(value.title || ''); const [description, setDescription] = useState(value.description || '');
  return <form className="card project-section" onSubmit={e => { e.preventDefault(); save({ id: value.id, title, description, archived: value.archived || false }); }}><label>Project name<input required maxLength={100} value={title} onChange={e => setTitle(e.target.value)} /></label><label>Description<textarea rows={3} maxLength={2000} value={description} onChange={e => setDescription(e.target.value)} /></label><div className="button-row"><button className="btn primary" disabled={busy}>Save project</button><button className="btn secondary" type="button" onClick={close}>Cancel</button></div></form>;
}
function NoteEditor({ value, busy, save, close }: { value: Partial<Note>; busy: boolean; save: (v: object) => void; close: () => void }) {
  const [title, setTitle] = useState(value.title || ''); const [body, setBody] = useState(value.body || '');
  function submit(e: FormEvent) { e.preventDefault(); save({ id: value.id, projectId: value.projectId, title, body }); }
  return <form className="note-editor" onSubmit={submit}><label>Note title<input required maxLength={180} value={title} onChange={e => setTitle(e.target.value)} /></label><label>Note<textarea rows={6} maxLength={4000} value={body} onChange={e => setBody(e.target.value)} /></label><div className="button-row"><button className="btn primary" disabled={busy}>Save note</button><button className="btn secondary" type="button" onClick={close}>Cancel</button></div></form>;
}
export function WorkspaceSettings({ state, act, busy }: { state: AppState; act: Act; busy: boolean }) {
  const [token, setToken] = useState(state.settings.mcpToken); const [clear, setClear] = useState(false);
  return <>
    <section className="card settings-card"><div className="kicker">MCP ACCESS</div><h2>Connect your assistant.</h2><p>Share your current focus session, saved tasks and ordinary browser tabs with a local MCP client. Excluded sites and private tabs are omitted. Page text, notes and connection keys are never sent.</p><label>MCP connection token<input type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} /></label><p className="small-label">Run npm run setup:mcp, then use the token in .local/mcp-token.txt. Start the MCP server from your client using docs/MCP.md.</p><button className="btn secondary" disabled={busy || !isExtension} onClick={() => act('MCP_SETTINGS', { settings: { mcpToken: token } })}>Save MCP token</button><label className="toggle-row"><span><strong>Allow MCP reading</strong><small>Applies only to this Chrome profile.</small></span><input type="checkbox" role="switch" disabled={busy || !isExtension} checked={state.settings.mcpEnabled} onChange={e => act('MCP_SETTINGS', { settings: { mcpEnabled: e.target.checked, mcpToken: token } })} /></label><label className="toggle-row"><span><strong>Allow MCP task changes</strong><small>Your connected assistant may create tasks and mark tasks done.</small></span><input type="checkbox" role="switch" disabled={busy || !isExtension || !state.settings.mcpEnabled} checked={state.settings.mcpWriteEnabled} onChange={e => act('MCP_SETTINGS', { settings: { mcpWriteEnabled: e.target.checked } })} /></label></section>
    <section className="card settings-card"><div className="kicker">WORKSPACE SYNC</div><h2>Pick up on another computer.</h2><p>Sync projects, tasks, saved links and notes through your Chrome account. Enable Chrome sync on each computer. Timers, history, AI settings, account connections and MCP permissions stay on this device.</p><label className="toggle-row"><span><strong>Sync workspace with Chrome</strong><small>For simultaneous edits to one item, the latest update wins. Local copies remain when sync is disabled.</small></span><input type="checkbox" role="switch" disabled={busy || !isExtension} checked={state.settings.syncEnabled} onChange={e => act('SYNC_SETTINGS', { enabled: e.target.checked })} /></label><p role="status">{state.sync.code === 'SYNC_READY' ? 'Saved to Chrome sync storage. Delivery depends on your Chrome account.' : state.sync.code === 'SYNC_OFF' ? 'Sync is off.' : state.sync.code === 'SYNC_PENDING' ? 'Sync pending…' : errorText(state.sync.code)}</p>{state.sync.at && <p className="small-label">Last local sync: {new Date(state.sync.at).toLocaleString()}</p>}<button className="btn secondary" disabled={busy || !state.settings.syncEnabled} onClick={() => act('SYNC_NOW')}>Sync now</button><p className="small-label">Chrome has a limited sync quota. Tabby reports capacity errors and keeps your local data.</p>{clear ? <div className="button-row"><button className="btn danger" disabled={busy} onClick={async () => { if (await act('SYNC_CLEAR', { confirm: true })) setClear(false); }}>Delete synced copy</button><button className="btn secondary" onClick={() => setClear(false)}>Cancel</button></div> : <button className="text-button danger-text" disabled={!isExtension} onClick={() => setClear(true)}>Remove data from Chrome sync</button>}<p className="small-label">Before removing the synced copy, turn off workspace sync on your other computers to prevent them from uploading it again. Clearing local data does not remove the synced copy.</p></section>
  </>;
}
export function AdvancedInsights({ state }: { state: AppState }) {
  const [days, setDays] = useState(7); const [project, setProject] = useState('');
  const data = analytics(state, days, project); const minutes = (n: number) => Math.round(n / 60000); const percent = (n: number | null) => n === null ? '—' : Math.round(n * 100) + '%';
  function download() { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), days, projectId: project || null, ...data }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'tabby-insights.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <section className="card project-section"><div className="card-top"><h2>Your recent rhythm</h2><button className="text-button" onClick={download}>Export report</button></div><div className="form-columns"><label>Period<select value={days} onChange={e => setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><label>Project filter<select value={project} onChange={e => setProject(e.target.value)}><option value="">All projects</option>{state.projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div><div className="insight-metrics"><div><strong>{minutes(data.observed)} min</strong><span>Observed time</span></div><div><strong>{percent(data.alignment)}</strong><span>On track / classified time</span></div><div><strong>{percent(data.coverage)}</strong><span>Classification coverage</span></div><div><strong>{data.completed}</strong><span>Tasks marked done</span></div></div><p className="muted">{data.sessions} sessions · {data.reminders} reminders · {data.returns} returns · longest session {minutes(data.longest)} min</p>{data.daily.length ? <div className="insights-table"><table><thead><tr><th>Date</th><th>Sessions</th><th>Observed</th><th>On track</th></tr></thead><tbody>{data.daily.map(d => <tr key={d.date}><td>{d.date}</td><td>{d.sessions}</td><td>{minutes(d.observed)} min</td><td>{minutes(d.aligned)} min</td></tr>)}</tbody></table></div> : <p>No sessions started in this period.</p>}<p className="small-label">Sessions are assigned to their start date in your local time zone. Project attribution is saved when focus starts or the goal changes. History is limited to 100 previous sessions; analytics stays on this device. On-track time is an observation, not a productivity score.</p></section>;
}
