import { chromium, expect } from '@playwright/test';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import assert from 'node:assert/strict';
import { createApp } from '../src/server/http';
import type { AppState } from '../src/shared/types';

const extensionPath = resolve('dist/extension');
const manifest = JSON.parse(await readFile(join(extensionPath, 'manifest.json'), 'utf8'));
const id = createHash('sha256').update(Buffer.from(manifest.key, 'base64')).digest('hex').slice(0, 32).replace(/[0-9a-f]/g, c => String.fromCharCode(97 + parseInt(c, 16)));
const token = 'TEST-ONLY-LOCAL-PAIRING-TOKEN-123456789';
const requests: any[] = []; let fail = false; let delayedResolve: (() => void) | undefined;
const provider = {
  status: async () => { if (fail) throw new Error('fixture unavailable'); return { connected: true, code: 'READY', model: 'TEST FIXTURE — not live Astra', available: [] }; },
  run: async (req: any) => {
    requests.push(req); if (fail) throw new Error('fixture unavailable');
    if (req.context.page?.title.includes('Delayed')) await new Promise<void>(resolve => { delayedResolve = resolve; });
    const category = /Cats/.test(req.context.page?.title || '') ? 'distracting' : /React/.test(req.context.page?.title || '') ? 'aligned' : 'unknown';
    let result: any = { category, reason: 'TEST FIXTURE: page-specific assessment', nextStep: 'TEST FIXTURE: add a login form.' };
    if (req.kind === 'next') result = { nextStep: 'TEST FIXTURE: add one input.' };
    if (req.kind === 'summary') result = { facts: ['TEST FIXTURE: session events available'], suggestions: ['TEST FIXTURE: review your goal'] };
    if (req.kind === 'task') result = { title: 'Extracted fixture task', steps: ['Review the source'], due: '', dueEvidence: '' };
    if (req.kind === 'groups') result = { groups: [{ title: 'Tabby test group', color: 'green', tabIds: req.context.tabs.slice(0, 2).map((t: any) => t.tabId) }] };
    return { result, model: 'TEST FIXTURE — not live Astra', usage: { total_tokens: 12 } };
  },
};
const api = createApp({ port: 4318, extensionId: id, pairToken: token }, provider as any);
const fixture = createServer((req, res) => {
  const name = req.url?.includes('cats') ? 'Cats entertainment video' : req.url?.includes('unknown') ? 'A page' : req.url?.includes('delayed') ? 'Delayed React tutorial' : 'React authentication tutorial';
  res.setHeader('Content-Type', 'text/html');
  res.end(`<html><head><title>${name}</title></head><body><main><h1>${name}</h1><p>Learn React authentication with a login form. This is a browser test fixture.</p><form><input id="private" value="NEVER_SEND_INPUT"><textarea>NEVER_SEND_TEXTAREA</textarea><p>NEVER_SEND_FORM</p></form><p hidden>NEVER_SEND_HIDDEN</p><p style="opacity:0">NEVER_SEND_INVISIBLE</p><p contenteditable>NEVER_SEND_EDITABLE</p><p>Contact hello@example.com</p></main></body></html>`);
});
await new Promise<void>(resolve => api.listen(4318, '127.0.0.1', resolve));
await new Promise<void>(resolve => fixture.listen(44320, '127.0.0.1', resolve));
const profile = await mkdtemp(join(tmpdir(), 'tabby-test-'));
const context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, viewport: { width: 1440, height: 1150 }, args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`] });
const logs: string[] = []; const checks: string[] = [];
const pass = (name: string) => { checks.push(name); console.log('PASS:', name); };
try {
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  worker.on('console', msg => { if (msg.type() === 'error') logs.push(msg.text()); });
  const panel = await context.newPage(); panel.on('pageerror', e => logs.push(e.message));
  await panel.goto(`chrome-extension://${id}/sidepanel.html`);
  const cmd = async (type: string, payload: Record<string, unknown> = {}) => panel.evaluate(async ({ type, payload }) => { const r = await chrome.runtime.sendMessage({ type, ...payload }); if (!r.ok) throw new Error(r.error); return r.data; }, { type, payload });
  const get = (): Promise<AppState> => cmd('GET');
  await expect(panel.locator('h1')).toHaveText('What matters today?');
  await mkdir('artifacts', { recursive: true }); await panel.screenshot({ path: 'artifacts/tabby-desktop.png', fullPage: true });
  await panel.setViewportSize({ width: 390, height: 1100 }); await panel.screenshot({ path: 'artifacts/tabby-panel.png', fullPage: true });
  assert.equal(await panel.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  pass('unpacked MV3 extension loads; desktop and 390px panel have no horizontal overflow');
  await panel.getByRole('button', { name: 'Tasks', exact: true }).click(); await panel.getByRole('button', { name: 'New task', exact: true }).click();
  await panel.getByLabel('Title', { exact: true }).fill('Build React authentication'); await panel.getByLabel('Short steps').fill('Create login form\nConnect test endpoint');
  await panel.getByRole('button', { name: 'Save task', exact: true }).click();
  assert.equal((await get()).tasks.length, 1); await panel.reload(); assert.equal((await get()).tasks[0].title, 'Build React authentication');
  pass('task creation through real UI and persistence after panel reload');
  await cmd('SETTINGS', { settings: { pairToken: token, consent: true, readText: true, mode: 'strict' } });
  await cmd('CONNECT'); assert.equal((await get()).ai.connected, true);
  pass('real Chrome extension Origin + local token accepted by loopback server');
  const panelOptions = await worker.evaluate(() => chrome.sidePanel.getOptions({}));
  const panelBehavior = await worker.evaluate(() => chrome.sidePanel.getPanelBehavior());
  assert.equal(panelOptions.path, 'sidepanel.html'); assert.equal(panelBehavior.openPanelOnActionClick, true);
  pass('native Side Panel path and extension action behavior are configured');
  const work = await context.newPage(); await work.goto('http://127.0.0.1:44320/watch?video=react'); await work.bringToFront();
  await cmd('START', { goal: 'Build React authentication', taskId: (await get()).tasks[0].id, minutes: 25 });
  await expect.poll(async () => (await get()).assessment?.category, { timeout: 18000 }).toBe('aligned');
  assert.ok(!JSON.stringify(requests).includes('NEVER_SEND')); assert.ok(!JSON.stringify(requests).includes('hello@example.com')); assert.ok(requests.some(r => r.context.page?.text));
  pass('8-second dwell then page assessment using explicit fixture; private form/hidden/editable text excluded');
  await panel.getByRole('button', { name: 'Focus', exact: true }).click(); await work.bringToFront(); await panel.screenshot({ path: 'artifacts/tabby-active-panel.png', fullPage: true });
  const cats = await context.newPage(); await cats.goto('http://127.0.0.1:44320/watch?video=cats'); await cats.bringToFront();
  await expect.poll(async () => (await get()).assessment?.category, { timeout: 18000 }).toBe('distracting');
  await expect(cats.locator('#tabby-reminder')).toHaveCount(1); await cats.locator('#private').evaluate((el: HTMLInputElement) => { el.value = 'USER_INPUT_RETAINED'; });
  pass('different videos on one host receive different fixture assessments; strict cover exists');
  await cmd('CORRECT'); assert.equal((await get()).assessment?.source, 'user'); await expect(cats.locator('#tabby-reminder')).toHaveCount(0); assert.equal(await cats.locator('#private').inputValue(), 'USER_INPUT_RETAINED');
  pass('This is relevant corrects exact context and removes cover without losing input');
  await cats.goto('http://127.0.0.1:44320/watch?video=cats-another');
  await expect.poll(async () => (await get()).assessment?.source, { timeout: 18000 }).toBe('ai');
  assert.equal((await get()).assessment?.category, 'distracting');
  fail = true; await cmd('CONNECT').catch(() => {}); await expect(cats.locator('#tabby-reminder')).toHaveCount(0); fail = false;
  pass('correction does not authorize another video; server outage releases strict restriction');
  await cmd('CONNECT'); await cmd('RETURN'); await expect.poll(async () => (await get()).page?.title, { timeout: 5000 }).toContain('React'); // Corrected video navigated; skip that now-changed context.
  await work.bringToFront(); await expect.poll(async () => (await get()).assessment?.category, { timeout: 18000 }).toBe('aligned');
  await cmd('CONFIRM_STEP', { step: 'Created login component' }); await cmd('BREAK', { minutes: 5 }); assert.equal((await get()).session?.phase, 'break');
  assert.equal((await get()).session?.lastConfirmedStep, 'Created login component');
  await cmd('RESUME'); await cmd('PAUSE'); const remaining = (await get()).session!.remainingMs; await panel.waitForTimeout(1100); assert.equal((await get()).session!.remainingMs, remaining);
  pass('break, context snapshot, resume and paused timer use persisted timestamps');
  await cmd('RESUME'); await work.bringToFront();
  const unknown = await context.newPage(); await unknown.goto('http://127.0.0.1:44320/unknown'); await unknown.bringToFront();
  await expect.poll(async () => (await get()).assessment?.category, { timeout: 18000 }).toBe('unknown'); await expect(unknown.locator('#tabby-reminder')).toHaveCount(0);
  pass('ambiguous page remains unclassified and unrestricted');
  const before = requests.length;
  await work.bringToFront(); await cats.bringToFront(); await work.bringToFront(); await panel.waitForTimeout(1200); assert.equal(requests.length, before);
  pass('rapid tab switching is coalesced; no API call before dwell');
  const delayed = await context.newPage(); await delayed.goto('http://127.0.0.1:44320/delayed'); await delayed.bringToFront();
  await expect.poll(() => !!delayedResolve, { timeout: 18000 }).toBe(true);
  await cmd('GOAL', { goal: 'Write a different task', taskId: '' }); delayedResolve!(); delayedResolve = undefined;
  await panel.waitForTimeout(400); assert.equal((await get()).assessment, null);
  pass('goal change cancels pending classification; stale response cannot apply');
  await work.bringToFront(); await cmd('AI', { kind: 'task' }); assert.equal((await get()).taskDraft?.title, 'Extracted fixture task'); assert.equal((await get()).taskDraft?.due, '');
  await cmd('CLEAR_DRAFT'); await cmd('AI', { kind: 'groups' }); assert.ok((await get()).groupDraft?.length);
  const firstGrouped = (await get()).groupDraft![0].tabIds[0];
  await worker.evaluate(async (tabId: number) => { const tab = await chrome.tabs.get(tabId); await chrome.tabs.update(tabId, { url: tab.url + '#changed-after-preview' }); }, firstGrouped);
  await panel.waitForTimeout(200); await assert.rejects(cmd('APPLY_GROUPS'), /TABS_CHANGED/);
  pass('grouping rejects a tab whose context changed after the preview');
  await cmd('AI', { kind: 'groups' }); await cmd('APPLY_GROUPS');
  const realGroups = await worker.evaluate(() => chrome.tabGroups.query({})); assert.ok(realGroups.some(g => g.title === 'Tabby test group' && g.color === 'green'));
  pass('task extraction produces editable draft; previewed grouping creates real Chrome groups');
  const dupe = await context.newPage(); await dupe.goto(work.url()); await work.bringToFront(); const tabList = await cmd('LIST_TABS') as Array<{id:number;url:string;active:boolean}>;
  const duplicate = tabList.find(t => t.url === work.url() && !t.active)!; assert.ok(duplicate);
  await cmd('CLOSE_DUPLICATES', { tabIds: [duplicate.id] }); assert.ok(!(await cmd('LIST_TABS') as any[]).some(t => t.id === duplicate.id));
  pass('explicit exact duplicate selection closes only chosen matching tab');
  await cmd('PAUSE'); const beforeRestart = (await get()).session!.remainingMs;
  const browserCdp = await context.browser()!.newBrowserCDPSession();
  const targets = await browserCdp.send('Target.getTargets'); const target = targets.targetInfos.find(t => t.type === 'service_worker' && t.url.includes(id));
  if (!target) throw new Error('Missing service worker target');
  await browserCdp.send('Target.closeTarget', { targetId: target.targetId });
  await expect.poll(async () => { try { return (await get()).session?.remainingMs; } catch { return -1; } }, { timeout: 10000 }).toBe(beforeRestart);
  assert.equal((await get()).tasks.length, 1);
  pass('actual service worker termination and restart preserves timer and tasks');
  await cmd('RESUME'); const runningBefore = (await get()).session!.remainingMs;
  const nextTargets = await browserCdp.send('Target.getTargets'); const nextTarget = nextTargets.targetInfos.find(t => t.type === 'service_worker' && t.url.includes(id));
  assert.ok(nextTarget); await browserCdp.send('Target.closeTarget', { targetId: nextTarget.targetId });
  await expect.poll(async () => { try { return (await get()).session?.phase; } catch { return ''; } }, { timeout: 10000 }).toBe('running');
  const restored = (await get()).session!; assert.ok(restored.remainingMs <= runningBefore && restored.remainingMs > runningBefore - 10000);
  pass('running session also recovers after real worker termination without resetting remaining time');
  await work.close(); await cmd('RETURN').catch(() => {});
  await cmd('STOP'); assert.equal((await get()).session?.phase, 'finished'); assert.equal(await cats.locator('#tabby-reminder').count(), 0);
  pass('closing work tab is handled; stopping session removes reminders');
  await panel.bringToFront(); await panel.getByRole('button', { name: 'Switch to English' }).click(); await expect(panel.getByRole('button', { name: 'Settings', exact: true })).toBeVisible();
  await panel.getByRole('button', { name: 'Settings', exact: true }).click(); await expect(panel.getByRole('heading', { name: 'Your focus. Your rules.' })).toBeVisible();
  assert.equal(await panel.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  pass('English interface and compact settings layout render correctly');
  assert.deepEqual(logs, []); pass('no page or service worker console errors');
  await writeFile('artifacts/browser-test-results.json', JSON.stringify({ type: 'Chrome integration with explicit fake AI responses; NOT live API validation', extensionId: id, checks, requestCount: requests.length, errors: logs }, null, 2));
} finally { delayedResolve?.(); await context.close(); api.closeAllConnections(); fixture.closeAllConnections(); await Promise.all([new Promise<void>(resolve => api.close(() => resolve())), new Promise<void>(resolve => fixture.close(() => resolve()))]); await rm(profile, { recursive: true, force: true }); }
