import { chromium, expect } from '@playwright/test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { mkdtemp, readFile, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { createHash } from 'node:crypto';
import { createServer } from 'node:http';
import assert from 'node:assert/strict';
import type { AppState } from '../src/shared/types';

const extensionPath = resolve('dist/extension'); const manifest = JSON.parse(await readFile(join(extensionPath, 'manifest.json'), 'utf8'));
const id = createHash('sha256').update(Buffer.from(manifest.key, 'base64')).digest('hex').slice(0, 32).replace(/[0-9a-f]/g, c => String.fromCharCode(97 + parseInt(c, 16)));
const profile = await mkdtemp(join(tmpdir(), 'tabby-workspace-')); const tokenFile = join(profile, 'test-mcp-token.txt');
const token = 'MCP-TEST-ONLY-NOT-A-PROVIDER-KEY-1234567890'; await writeFile(tokenFile, token, { mode: 0o600 });
const fixture = createServer((_req, res) => { res.setHeader('Content-Type', 'text/html'); res.end('<html><head><title>Tabby real browser test page</title></head><body>Local browser fixture; no AI provider calls.</body></html>'); });
await new Promise<void>(resolve => fixture.listen(44330, '127.0.0.1', resolve));
const context = await chromium.launchPersistentContext(join(profile, 'chrome'), { channel: 'chromium', headless: true, viewport: { width: 390, height: 844 }, args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`] });
const checks: string[] = []; const errors: string[] = []; let providerCalls = 0;
context.on('request', req => { if (req.url().includes(':4318/ai')) providerCalls++; });
const pass = (s: string) => { checks.push(s); console.log('PASS:', s); };
const transport = new StdioClientTransport({ command: process.execPath, args: ['--import', resolve('node_modules/tsx/dist/loader.mjs'), resolve('src/mcp/index.ts')], cwd: tmpdir(), env: { ...Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined)), TABBY_MCP_TOKEN_FILE: tokenFile }, stderr: 'pipe' });
const client = new Client({ name: 'tabby-workspace-verification', version: '1.0.0' });
try {
  await client.connect(transport); const listed = await client.listTools(); assert.equal(listed.tools.length, 5);
  const call = async (name: string, args: Record<string, unknown> = {}) => client.callTool({ name, arguments: args });
  const data = async (name: string, args: Record<string, unknown> = {}) => { const result = await call(name, args); assert.ok(!result.isError, JSON.stringify(result)); return result.structuredContent as any; };
  const panel = await context.newPage(); panel.on('pageerror', e => errors.push(e.message));
  await panel.goto(`chrome-extension://${id}/sidepanel.html`);
  const cmd = async (type: string, payload: Record<string, unknown> = {}) => panel.evaluate(async ({ type, payload }) => { const r = await chrome.runtime.sendMessage({ type, ...payload }); if (!r.ok) throw new Error(r.error); return r.data; }, { type, payload });
  const get = (): Promise<AppState> => cmd('GET');
  assert.ok((await call('tabby_get_session')).isError);
  await panel.getByRole('button', { name: 'Projects', exact: true }).click();
  await panel.getByRole('button', { name: 'New project', exact: true }).click();
  await panel.getByLabel('Project name', { exact: true }).fill('MCP verified project'); await panel.getByLabel('Description', { exact: true }).fill('A real project saved through the extension UI.');
  await panel.getByRole('button', { name: 'Save project', exact: true }).click(); await expect(panel.getByRole('heading', { name: 'MCP verified project', exact: true })).toBeVisible();
  const projectId = (await get()).projects[0].id;
  await panel.getByRole('button', { name: 'Add task', exact: true }).click(); await panel.getByLabel('Title', { exact: true }).fill('Manual task from installed Tabby'); await panel.getByRole('button', { name: 'Save task', exact: true }).click();
  assert.equal((await get()).tasks[0].projectId, projectId); const manualId = (await get()).tasks[0].id;
  await panel.getByRole('button', { name: 'Projects', exact: true }).click(); await panel.getByLabel('Selected project').selectOption(projectId);
  await panel.getByRole('button', { name: 'New note', exact: true }).click(); await panel.getByLabel('Note title', { exact: true }).fill('Return here'); await panel.getByLabel('Note', { exact: true }).fill('Keep the original thought.\nSecond line.'); await panel.getByRole('button', { name: 'Save note', exact: true }).click();
  await expect(panel.getByRole('heading', { name: 'Return here', exact: true })).toBeVisible();
  const page = await context.newPage(); await page.goto('http://127.0.0.1:44330/reference?token=DO_NOT_EXPORT#fragment');
  const tabId = await panel.evaluate(async () => (await chrome.tabs.query({})).find(t => t.url?.includes(':44330/reference'))!.id!);
  await panel.bringToFront(); await panel.getByRole('button', { name: 'Refresh', exact: true }).click(); await panel.getByLabel('Tab to pin').selectOption(String(tabId)); await panel.getByRole('button', { name: 'Pin tab', exact: true }).click();
  assert.equal((await get()).pinnedTabs[0].url, 'http://127.0.0.1:44330/reference');
  await mkdir('artifacts', { recursive: true }); await panel.screenshot({ path: 'artifacts/tabby-projects.png', fullPage: true });
  assert.equal(await panel.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.ok((await panel.locator('nav').boundingBox())!.height < 100, 'Compact panel navigation must remain one row');
  pass('real extension UI creates a project, linked task, multiline note and sanitized pinned tab at 390px');
  await cmd('START', { goal: 'Verify MCP against installed Tabby', taskId: manualId, minutes: 25 }); await cmd('PAUSE');
  await cmd('SETTINGS', { settings: { consent: false, pairToken: 'LOCAL-AI-TOKEN-MUST-NOT-LEAK' } });
  await cmd('MCP_SETTINGS', { settings: { mcpEnabled: true, mcpToken: token } });
  await expect.poll(async () => (await call('tabby_get_session')).isError === true, { timeout: 10000 }).toBe(false);
  const session = await data('tabby_get_session'); assert.equal(session.session.goal, 'Verify MCP against installed Tabby'); assert.equal(session.session.projectId, projectId);
  const tasks = await data('tabby_list_tasks'); assert.ok(tasks.tasks.some((t: any) => t.id === manualId));
  const tabs = await data('tabby_list_tabs'); assert.ok(tabs.tabs.some((t: any) => t.id === tabId)); assert.ok(tabs.tabs.every((t: any) => /^https?:/.test(t.url)));
  const exports = JSON.stringify([session, tasks, tabs]); for (const marker of [token, 'LOCAL-AI-TOKEN-MUST-NOT-LEAK', 'DO_NOT_EXPORT', 'Second line']) assert.ok(!exports.includes(marker));
  pass('official SDK tools/list and tools/call read the real saved task, paused session and Chrome tab without credentials or note text');
  const requestId = crypto.randomUUID(); const input = { requestId, title: 'Created over MCP', projectId };
  assert.ok((await call('tabby_create_task', input)).isError); await cmd('MCP_SETTINGS', { settings: { mcpWriteEnabled: true } });
  const created = await data('tabby_create_task', input); const replayed = await data('tabby_create_task', input); assert.equal(created.task.id, replayed.task.id); assert.equal(replayed.replayed, true);
  assert.equal((await get()).tasks.filter(t => t.title === input.title).length, 1);
  assert.ok((await call('tabby_create_task', { ...input, title: 'Changed intent' })).isError);
  const complete = { requestId: crypto.randomUUID(), taskId: created.task.id }; const done = await data('tabby_complete_task', complete); assert.equal(done.task.status, 'done');
  assert.equal((await data('tabby_complete_task', complete)).task.completedAt, done.task.completedAt);
  assert.equal((await get()).tasks.find(t => t.id === created.task.id)?.status, 'done');
  pass('MCP write permission, create/complete, duplicate retries and conflicting request IDs enforce real persisted behavior');
  await cmd('SETTINGS', { settings: { excludedSites: ['127.0.0.1'] } }); assert.equal((await data('tabby_list_tabs')).tabs.length, 0);
  await assert.rejects(cmd('PIN_TAB', { projectId, tabId }), /PAGE_UNAVAILABLE/); await assert.rejects(cmd('OPEN_PIN', { id: (await get()).pinnedTabs[0].id }), /PAGE_UNAVAILABLE/);
  await cmd('SETTINGS', { settings: { excludedSites: [] } });
  await page.close(); await cmd('OPEN_PIN', { id: (await get()).pinnedTabs[0].id });
  assert.ok(await panel.evaluate(async () => (await chrome.tabs.query({})).some(t => t.url === 'http://127.0.0.1:44330/reference')));
  pass('excluded sites are omitted from MCP and blocked for pin/open; saved links reopen only on explicit command');
  await cmd('SYNC_SETTINGS', { enabled: true }); await expect.poll(async () => (await get()).sync.code).toBe('SYNC_READY');
  const synced = await panel.evaluate(() => chrome.storage.sync.get(null)); assert.ok(Object.keys(synced).some(k => k.includes(':task:')));
  assert.ok(!JSON.stringify(synced).includes(token)); assert.ok(!JSON.stringify(synced).includes('LOCAL-AI-TOKEN-MUST-NOT-LEAK'));
  const noteId = (await get()).notes[0].id;
  await panel.evaluate(async ({ noteId }) => { const key = 'tabby:v1:note:' + noteId; const data = await chrome.storage.sync.get(key); const note = data[key] as Record<string, unknown>; await chrome.storage.sync.set({ [key]: { ...note, body: 'Received from a simulated second device', updatedAt: Date.now() + 1000 } }); }, { noteId });
  await expect.poll(async () => (await get()).notes[0].body).toBe('Received from a simulated second device');
  await cmd('DELETE_NOTE', { id: noteId }); await expect.poll(async () => panel.evaluate(async noteId => { const value = (await chrome.storage.sync.get('tabby:v1:note:' + noteId))['tabby:v1:note:' + noteId] as Record<string, unknown>; return !!value?.deletedAt; }, noteId)).toBe(true);
  pass('actual chrome.storage.sync publishes allowlisted records and merges remote edits/deletions; cloud delivery is not simulated as verified');
  // Stop the real MV3 worker, then wake it through the panel. Receipts and state survive.
  const cdp = await context.newCDPSession(panel); const versions: any[] = [];
  cdp.on('ServiceWorker.workerVersionUpdated', ({ versions: next }) => versions.push(...next)); await cdp.send('ServiceWorker.enable');
  await expect.poll(() => versions.some(v => v.scriptURL === `chrome-extension://${id}/worker.js` && v.runningStatus === 'running')).toBe(true);
  const version = [...versions].reverse().find(v => v.scriptURL === `chrome-extension://${id}/worker.js` && v.runningStatus === 'running');
  await cdp.send('ServiceWorker.stopWorker', { versionId: version.versionId }); await cmd('GET');
  await expect.poll(async () => (await call('tabby_list_tasks')).isError === true, { timeout: 35000 }).toBe(false);
  const afterRestart = await data('tabby_create_task', input); assert.equal(afterRestart.task.id, created.task.id); assert.equal(afterRestart.replayed, true);
  assert.equal((await get()).projects[0].id, projectId);
  pass('real service worker termination and restart retain workspace and MCP idempotency receipts');
  await panel.bringToFront(); await panel.getByRole('button', { name: 'Insights', exact: true }).click(); await expect(panel.getByRole('heading', { name: 'Your recent rhythm' })).toBeVisible();
  await panel.screenshot({ path: 'artifacts/tabby-insights.png', fullPage: true });
  await panel.getByRole('button', { name: 'Settings', exact: true }).click(); await expect(panel.getByRole('switch', { name: /Allow MCP reading/ })).toBeChecked();
  await panel.getByRole('switch', { name: /Allow MCP reading/ }).click(); await expect.poll(async () => (await call('tabby_get_session')).isError).toBe(true);
  assert.equal((await get()).settings.mcpWriteEnabled, false);
  await cmd('SYNC_CLEAR', { confirm: true }); assert.equal(Object.keys(await panel.evaluate(() => chrome.storage.sync.get(null))).filter(k => k.startsWith('tabby:v1:')).length, 0);
  assert.ok((await get()).tasks.length > 0); assert.equal(providerCalls, 0); assert.deepEqual(errors, []);
  pass('settings revoke MCP reads/writes, synced copy removal preserves local tasks, analytics renders, no page errors or AI requests');
  await writeFile('artifacts/workspace-test-results.json', JSON.stringify({ passed: checks.length, checks, mcpClient: '@modelcontextprotocol/sdk 1.30.0 via stdio', actualChrome: true, aiProviderCalls: providerCalls, cloudSyncDeliveryVerified: false }, null, 2));
} finally { await client.close().catch(() => {}); await context.close(); fixture.closeAllConnections(); await new Promise<void>(resolve => fixture.close(() => resolve())); await rm(profile, { recursive: true, force: true }); }
