import { useEffect, useState } from 'react';
import {
  ArrowRight, ArrowUpRight, Check, ChevronDown,
  Coffee, Command, FolderOpen, Heart, Leaf, Menu,
  MousePointer2, Play, Plus, ShieldCheck, Sparkles, X,
} from 'lucide-react';
import { BrandLogo, Cat, ChromeIcon, Modal, ToolIcon } from './components';
import { Workspace, useWorkspace } from './Workspace';
import { ExtraFeatureCards, FeatureExplorer, UpcomingDetails } from './ProductFeatures';
import { DemoVideo } from './DemoVideo';
import { InstallationGuide } from './InstallationGuide';

const integrations = [
  { name: 'Gmail', icon: 'gmail', available: true }, { name: 'Google Calendar', icon: 'calendar', available: true },
  { name: 'Notion', icon: 'notion', available: false }, { name: 'Slack', icon: 'slack', available: false },
  { name: 'Linear', icon: 'linear', available: false }, { name: 'Todoist', icon: 'todoist', available: false },
];

const faqs = [
  { q: "Okay, what exactly is Tabby?", a: "Tabby is a little home for your attention: tasks, projects, notes, useful links, and focus sessions. The developer Chrome extension also includes contextual nudges, AI chat, local MCP tools, Google connectors, optional Chrome workspace sync, and reports. This website has a separate no-install preview of tasks, a timer, example tab spaces, and progress." },
  { q: "Can I try it without signing up?", a: "Absolutely. Choose “See it in action” for the no-install preview. Add a task, check something off, or start a timer. “Try Tabby” opens the extension installation guide. There’s no account to create and no credit card to reach for." },
  { q: "What can I do with tasks and projects?", a: "Create and edit tasks with up to eight steps, a due date, a source link, a project, and Planned, In progress, or Done status. Reopen a completed task or start focus from it. A project keeps its tasks, multiline notes, and saved tab links together; archive and restore projects without losing their contents. The website preview has a simpler task list, including search, filters, and deletion." },
  { q: "Will it organize my actual browser tabs?", a: "In the extension, search and switch tabs in the current window, review AI grouping suggestions, and create real Chrome tab groups. Select exact duplicates to close while keeping a copy; active and pinned tabs are protected. You can also save cleaned links inside projects and explicitly reopen them later. Saving a project link does not pin a Chrome tab in the tab strip. The website preview uses example links." },
  { q: "How does Tabby know what counts as a distraction?", a: "During focus, the extension compares a page with your goal and task using the context you allow it to share. A React tutorial and a cat video on the same site can have different relevance. Get a reason, correct the suggestion, and choose a soft reminder or reversible cover. AI needs your configured service; page text and site permissions are separate choices." },
  { q: "Can I turn text from a page into a task?", a: "Select text and choose Tabby from Chrome’s context menu. Keep it as a task or ask AI for an editable draft and steps. Review before saving. The source stays attached, and an AI-suggested deadline needs an explicit date in the selected text. In connected Gmail or Calendar, you can also import a chosen item; repeat imports reuse the saved task." },
  { q: "What happens when I take a break?", a: "The extension keeps your goal, working tabs, and last confirmed step. After a timed break, a resume card helps you pick up the thread. You choose when to continue, and can ask AI for one next step. The website preview has a simpler timer with pause, resume, and reset." },
  { q: "Can my AI assistant work with Tabby through MCP?", a: "Yes, through a local stdio MCP client and the installed extension. Five tools read your focus session, tasks, and ordinary tabs, or create and complete tasks. Task reads support status and project filters. Reading is opt-in; creating and completing tasks requires a separate permission. Once enabled, those writes do not ask for another in-panel click. Retry protection avoids duplicate actions. MCP itself makes no AI-provider calls." },
  { q: "Which assistants can connect, and what can they see?", a: "The official MCP SDK client is verified, and setup instructions cover Claude Desktop; the Claude Desktop interface itself has not been tested. The bridge is local, so cloud-hosted ChatGPT cannot connect to it directly. It omits private, internal, and excluded tabs and never exports notes, page text, Google snapshots, or connection keys. You can turn off access in Settings." },
  { q: "Can I chat with my tasks?", a: "Yes. The extension saves an ongoing AI conversation about your tasks and current goal, with suggested prompts, replies in your language, cancel, and retry. It can propose creating a task, completing one, or starting focus. Each proposal needs your click and cannot apply twice; stale proposals are rejected. Calendar context is a separate opt-in. Chat needs AI consent and your provider connection." },
  { q: "What do Calendar and Gmail actually do?", a: "With Google OAuth configured, Calendar shows the next 14 days from your primary calendar, up to 250 events, a next-meeting view, event links, refresh, and task import. Gmail shows the latest 20 inbox previews and lets you import a task or review an AI draft. It does not fetch full email bodies or attachments, send mail, mark it read, or edit events. These connectors are experimental: live Google sign-in and account data still need verification." },
  { q: "Which tools are still coming?", a: "Notion, Linear, Todoist, and TickTick task connections remain planned, along with Slack, Telegram, and WhatsApp inboxes and automatic background collection across apps. Current Google imports and webpage capture start with your choice. MCP, AI chat, projects, Chrome workspace sync, and reports are already part of the developer extension." },
  { q: "Can my workspace follow me to another computer?", a: "There is optional Chrome account sync for projects, tasks, notes, and saved links. Enable it on each computer with Chrome sync and the same extension ID. Timers, history, analytics, account connections, credentials, and permissions stay local. Delivery between real signed-in computers is not yet verified. Chrome quotas apply, and the latest update wins when two devices edit one item." },
  { q: "What do the insights actually measure?", a: "Session insights separate focus, distractions, uncertain context, breaks, pauses, and time away, with reminders, returns, and an optional AI recap. Reports cover 7, 30, or 90 days, filter by project, and export JSON. They include daily observed time, task completions, classification coverage, and the longest session. History is capped at 100 previous sessions, so long-range reports may be incomplete. Recorded time is not proof of productivity; the decorative weekly chart is an illustration." },
  { q: "What happens to the tasks I add?", a: "Website preview tasks stay in this browser. The extension stores its own workspace locally; turning on Chrome workspace sync also sends project, task, note, and saved-link records through Chrome. AI receives only the context authorized for that action. Google connections and chat remain local, outside workspace sync. Turning sync off keeps local records; removing the synced copy also keeps your local workspace." },
  { q: "Is Tabby free?", a: "The website preview is free, and the developer extension has no subscription checkout. Projects, notes, MCP, chat, Chrome workspace sync, and reports are not locked behind a paid Plus plan. AI uses your own provider connection and may incur usage charges; Google needs its own OAuth setup. The Plus card is a look at planned connections, not a payment offer. No payment is collected here." },
];

export default function App() {
  const workspace = useWorkspace();
  const [menuOpen, setMenuOpen] = useState(false);
  const [modal, setModal] = useState<'workspace' | 'plus' | 'privacy' | 'extension' | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [demoActive, setDemoActive] = useState(false);

  const openWorkspace = () => { setMenuOpen(false); setModal('workspace'); };
  const openInstall = () => { setMenuOpen(false); setModal('extension'); };
  const seeDemo = () => {
    setMenuOpen(false);
    document.getElementById('workspace')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'center' });
    setDemoActive(true);
    window.setTimeout(() => setDemoActive(false), 2400);
  };

  useEffect(() => {
    const elements = document.querySelectorAll('.reveal');
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); }
    }), { threshold: .12 });
    elements.forEach(element => observer.observe(element));
    const keyboard = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault(); setModal(current => current === 'workspace' ? null : 'workspace');
      }
      if (event.key === 'Escape') setMenuOpen(false);
    };
    document.addEventListener('keydown', keyboard);
    return () => { observer.disconnect(); document.removeEventListener('keydown', keyboard); };
  }, []);

  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="announcement"><span className="announcement-pill">MEET TABBY</span><span>A fresh start for your busy browser.</span><button onClick={seeDemo}>Find your flow <ArrowUpRight size={13} /></button></div>
    <header className="site-header">
      <a href="#" className="brand" aria-label="Tabby home"><BrandLogo /></a>
      <nav className="desktop-nav" aria-label="Main navigation"><a href="#features">Why Tabby</a><a href="#mcp">MCP</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a></nav>
      <div className="header-actions"><button className="button button-small button-dark" onClick={openInstall}>Try Tabby <ArrowUpRight size={15} /></button><button className="mobile-menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-nav">{menuOpen ? <X /> : <Menu />}</button></div>
      {menuOpen && <nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{[['Why Tabby', '#features'], ['MCP', '#mcp'], ['How it works', '#how-it-works'], ['Pricing', '#pricing'], ['FAQs', '#faq']].map(([name, href]) => <a href={href} key={href} onClick={() => setMenuOpen(false)}>{name}<ArrowUpRight size={18} /></a>)}<button onClick={openInstall}>Make yourself at home <ArrowRight size={18} /></button></nav>}
    </header>

    <main id="main">
      <section className="hero" aria-labelledby="hero-title">
        <div className="hero-copy">
          <div className="eyebrow hero-eyebrow"><span className="mini-sparkle">✳</span> YOUR BROWSER’S NEW BEST FRIEND</div>
          <h1 id="hero-title">Less chaos.<br />More <span className="focus-word">focus.<svg className="focus-underline" viewBox="0 0 340 20" fill="none" aria-hidden="true"><path d="M4 12C88-2 227-2 335 8M34 18c78-11 166-9 235-5" stroke="currentColor" strokeWidth="5" strokeLinecap="round" /></svg><span className="hero-asterisk" aria-hidden="true">✳</span></span></h1>
          <p>Too many tabs. Too much on your mind.<br />Meet the little sidekick that brings it all together.</p>
          <div className="hero-buttons"><button className="button button-orange" onClick={openInstall}><ChromeIcon size={21} /> Try Tabby for free <ArrowUpRight size={18} /></button><button className="button button-plain" onClick={seeDemo}><span className="play-circle"><Play size={10} fill="currentColor" /></span> See it in action</button></div>
          <div className="hero-note"><Check size={12} /> No credit card <span>·</span> No tab-shaming <span>·</span> Just a clearer head</div>
          <div className="floating-note note-left" aria-hidden="true"><div className="mini-tab mini-tab-back"><ToolIcon name="gmail" size={17} /> Inbox (128) <X size={12} /></div><div className="mini-tab"><ToolIcon name="notion" size={17} /> That one good idea <X size={12} /></div><div className="note-caption">a familiar situation?<svg width="56" height="51" viewBox="0 0 56 51" fill="none"><path d="M2 3c38 2 40 23 28 42m-4-10 4 11 11-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg></div></div>
          <div className="floating-note note-right" aria-hidden="true"><div className="focus-sticker"><span className="sticker-star">✦</span><Cat size={39} variant="sticker" /><span>in my focus era</span><span className="sticker-star second-star">✦</span></div><span className="little-cross">+</span></div>
        </div>

        <div className={`workspace-stage ${demoActive ? 'demo-highlight' : ''}`} id="workspace">
          <div className="stage-topline"><span><span className="stage-dot" /> A LITTLE SPACE FOR YOUR BIG IDEAS</span><button onClick={openWorkspace}>Open your workspace <ArrowUpRight size={14} /></button></div>
          <div className="stage-doodle doodle-one" aria-hidden="true">✳</div><div className="stage-doodle doodle-two" aria-hidden="true">✳</div>
          <Workspace state={workspace} />
          <div className="stage-bottomline"><span><MousePointer2 size={13} /> A real little preview. Go ahead, click around.</span><span>LESS BUSY. MORE YOU. <span>↗</span></span></div>
        </div>
        <div className="under-stage"><span><Leaf size={14} /> A lighter way to work</span><span><ShieldCheck size={14} /> Your peace of mind comes first</span><span><Heart size={14} /> Made for wonderfully busy brains</span></div>
      </section>

      <DemoVideo />

      <section className="integrations-section section-wrap reveal" aria-label="Connections and integrations"><p>All your favorite tools.<span> Finally on the same page.</span></p><div className="integration-logos">{integrations.map(tool => <div key={tool.icon}><ToolIcon name={tool.icon} size={26} /><span><strong>{tool.name}</strong><small className={`integration-state ${tool.available ? 'current' : ''}`}>{tool.available ? 'Developer setup' : 'Planned'}</small></span></div>)}</div><span className="integration-caption">Gmail and Google Calendar are implemented in the developer extension with separate OAuth setup. More of your everyday apps are on the roadmap.</span><div className="integration-future-tools"><span>Also on the roadmap</span><span>TickTick</span><span>Telegram</span><span>WhatsApp</span></div><div className="integration-verification">Experimental Google connectors · Live account sign-in is not yet verified.</div></section>

      <section className="features-section section-wrap" id="features" aria-labelledby="features-title">
        <div className="section-heading reveal"><div><div className="eyebrow"><span>✳</span> A CLEARER KIND OF EVERYDAY</div><h2 id="features-title">Big things happen<br />with a little <span className="serif-word">headspace.</span></h2></div><p>Your brain is for brilliant ideas.<br />Let Tabby handle the other stuff.</p></div>
        <div className="feature-grid">
          <article className="feature-card collection-card reveal"><div className="feature-copy"><div className="feature-top"><span className="feature-number">01 / BRING IT TOGETHER</span><span className="small-pill">GOOGLE SETUP REQUIRED</span></div><h3>One home for<br />everything on your mind.</h3><p>Bring a chosen email or event into your tasks.<br />Ask for an AI draft. Review it. Make it yours.</p></div><div className="collection-visual" aria-hidden="true"><div className="connection-icons"><span><ToolIcon name="gmail" size={32} /></span><span><ToolIcon name="calendar" size={30} /></span><span><Cat size={29} variant="task" /></span><span><FolderOpen size={29} /></span></div><svg className="connection-lines" viewBox="0 0 480 84" fill="none"><path d="M60 0v22q0 12 12 12h156q12 0 12 12v38M180 0v20q0 14 14 14h34q12 0 12 12M300 0v20q0 14-14 14h-34q-12 0-12 12M420 0v22q0 12-12 12H252q-12 0-12 12v38" stroke="#d7d6cb" strokeWidth="1.5" strokeDasharray="4 4" /></svg><div className="collection-task"><span className="collection-cat"><Cat size={29} variant="collection" /></span><div><strong>Everything’s right here.</strong><span>Your ideas have a new home.</span></div><span className="collection-check"><Check size={17} /></span></div></div></article>

          <article className="feature-card deep-work-card reveal"><div className="feature-copy"><span className="feature-number">02 / FIND YOUR FLOW</span><h3>Meet your<br />do-not-disturb era.</h3><p>Flexible sessions, a pause, and a well-earned break.<br />Come back to your goal and your last good step.</p></div><div className="deep-work-visual"><div className="timer-orbit orbit-one" /><div className="timer-orbit orbit-two" /><div className="timer-orbit orbit-three" /><span className="orbit-star star-one">✦</span><span className="orbit-star star-two">✦</span><div className="feature-timer"><span><i />{workspace.running ? 'IN YOUR ELEMENT' : 'A MOMENT OF CLARITY'}</span><strong>{String(Math.floor(workspace.seconds / 60)).padStart(2, '0')}<span>:</span>{String(workspace.seconds % 60).padStart(2, '0')}</strong><button onClick={workspace.toggleTimer}>{workspace.running ? 'Pause your session' : 'Let’s get into it'}{workspace.running ? <span>Ⅱ</span> : <Play size={12} fill="currentColor" />}</button></div><div className="focus-notification"><span><ShieldCheck size={15} /></span> You’ve got this. One thing at a time.</div></div></article>

          <article className="feature-card tabs-card reveal"><div className="feature-copy"><span className="feature-number">03 / TAME THE TAB CHAOS</span><h3>37 tabs. Zero panic.</h3><p>Search your tabs, group projects, clear duplicates.<br />A home for every rabbit hole, in the extension.</p></div><div className="tabs-visual" aria-hidden="true"><div className="visual-tab-group group-purple"><div><span><FolderOpen size={15} /> The next big thing</span><span>3 tabs <ChevronDown size={13} /></span></div><div className="visual-tab-items"><span><ToolIcon name="figma" size={19} /> Brand explorations</span><span><ToolIcon name="notion" size={18} /> A very good idea</span><span><ToolIcon name="linear" size={17} /> Let’s make it happen</span></div></div><div className="visual-tab-group group-green"><div><span><FolderOpen size={15} /> For a rainy day</span><span>12 tabs <ChevronDown size={13} /></span></div></div><div className="visual-tab-group group-orange"><div><span><FolderOpen size={15} /> Life stuff</span><span>8 tabs <ChevronDown size={13} /></span></div></div><div className="floating-cursor"><MousePointer2 size={19} fill="currentColor" /><span>you, but organized</span></div></div></article>

          <article className="feature-card rhythm-card reveal"><div className="feature-copy"><span className="feature-number">04 / FEEL GOOD ABOUT YOUR DAY</span><h3>Progress, without<br />the pressure.</h3><p>Session recaps and 7, 30, or 90-day project reports.<br />Export your progress. Be kinder to your mind.</p></div><div className="rhythm-visual" aria-hidden="true"><div className="visual-chart-title"><span>Your focus is growing <span>↗</span></span><span>A LITTLE, EVERY DAY</span></div><div className="visual-bars">{[38, 60, 46, 78, 62, 91, 72].map((height, i) => <div key={i}><div className={`visual-bar ${i === 5 ? 'highlight' : ''}`} style={{ height: `${height}%` }}>{i === 5 && <span>Nice work ✦</span>}</div><span>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</span></div>)}</div><div className="chart-note"><span><Leaf size={14} /> Progress looks different every day.</span><small>ILLUSTRATION</small></div></div></article>
          <ExtraFeatureCards onExtension={() => setModal('extension')} />
        </div>
        <div className="features-footer reveal"><span><ShieldCheck size={17} /> A calm space, with your privacy in mind.</span><button onClick={() => setModal('privacy')}>Here’s how <ArrowUpRight size={15} /></button></div>
      </section>

      <FeatureExplorer onDemo={openWorkspace} onExtension={() => setModal('extension')} />

      <section className="how-section" id="how-it-works" aria-labelledby="how-title"><div className="section-wrap"><div className="how-heading reveal"><div className="eyebrow"><span>↗</span> LESS SETUP. MORE SHOWING UP.</div><h2 id="how-title">Find your flow.<br /><span className="serif-word">Keep your curious.</span></h2><p>No new system to master. Just a better place to start.</p></div><div className="steps-grid"><article className="step reveal"><span className="step-index">01</span><div className="step-icon"><ChromeIcon size={28} /></div><h3>Make yourself at home.</h3><p>Open Tabby and take a look around.<br />Your next clear-headed day starts here.</p><span className="step-arrow"><ArrowRight size={30} strokeWidth={1} /></span></article><article className="step reveal"><span className="step-index">02</span><div className="step-icon"><ListVisual /></div><h3>Let a little order in.</h3><p>A home for your tasks. A space for your tabs.<br />Suddenly, it all feels a little lighter.</p><span className="step-arrow"><ArrowRight size={30} strokeWidth={1} /></span></article><article className="step reveal"><span className="step-index">03</span><div className="step-icon"><Sparkles size={29} /></div><h3>Do your kind of great.</h3><p>Start a timer. Pick one thing.<br />You bring the ideas. We’ll bring the calm.</p></article></div><button className="button button-dark reveal" onClick={openInstall}>Sounds like my kind of day <ArrowUpRight size={17} /></button></div></section>

      <section className="for-you-section section-wrap"><div className="section-heading reveal"><div><div className="eyebrow"><span>♡</span> FOR BEAUTIFULLY BUSY MINDS</div><h2>Whatever you’re into.<br /><span className="serif-word">Get a little more into it.</span></h2></div><p>Side projects. Big deadlines. Wild ideas.<br />There’s room for all of you here.</p></div><div className="audience-grid"><article className="audience-card reveal"><span className="audience-symbol">✳</span><span className="audience-label">FOR THE MAKERS</span><h3>Less admin.<br />More “I made this.”</h3><p>Keep the project moving and the inspiration close. Your next great thing deserves your attention.</p><div className="audience-bottom"><span>Make something good</span><ArrowUpRight size={18} /></div></article><article className="audience-card reveal"><span className="audience-symbol book-symbol">▤</span><span className="audience-label">FOR THE LEARNERS</span><h3>Go down the<br />right rabbit hole.</h3><p>Give your research a home and your study sessions a rhythm. Curiosity looks good on you.</p><div className="audience-bottom"><span>Stay wonderfully curious</span><ArrowUpRight size={18} /></div></article><article className="audience-card reveal"><span className="audience-symbol">↗</span><span className="audience-label">FOR THE MULTITASKERS</span><h3>A busy mind.<br />A calmer day.</h3><p>For all the hats you wear and all the things you do. Find a little breathing room between them.</p><div className="audience-bottom"><span>Make room for you</span><ArrowUpRight size={18} /></div></article></div></section>

      <section className="pricing-section section-wrap" id="pricing" aria-labelledby="pricing-title"><div className="center-heading reveal"><div className="eyebrow"><span>✦</span> LESS FRICTION. MORE FOCUS.</div><h2 id="pricing-title">A clearer head.<br /><span className="serif-word">A pretty easy yes.</span></h2><p>Start with a little headspace. Make yourself at home.</p></div><div className="pricing-grid"><article className="pricing-card reveal"><div className="pricing-plan"><span><Cat size={23} /> Tabby Free</span><span className="small-pill">YOURS TO EXPLORE</span></div><h3>$0<span> / forever</span></h3><p>A small step toward a much calmer day.</p><button className="button button-dark" onClick={openWorkspace}>Find your focus <ArrowUpRight size={17} /></button><ul><li><Check />Your own to-do list</li><li><Check />Flexible 5, 25 & 45 minute focus sessions</li><li><Check />Example tab spaces to explore</li><li><Check />A little view of your progress</li><li><Check />No account needed</li></ul><div className="pricing-note"><Heart size={13} /> Good focus should feel this easy.</div></article><article className="pricing-card plus-card reveal"><div className="pricing-plan"><span><Sparkles size={21} /> Tabby Plus</span><span className="small-pill">COMING SOON</span></div><h3>A little more <span className="plus-sparkle">✳</span></h3><p>For your next big idea. And the one after that.</p><button className="button button-outline" onClick={() => setModal('plus')}>Meet what’s next <ArrowUpRight size={17} /></button><span className="planned-label">IN THE WORKS</span><ul><li><Plus />Automatic tasks from connected apps</li><li><Plus />Notion & Linear task connections</li><li><Plus />Todoist & TickTick task connections</li><li><Plus />Slack, Telegram & WhatsApp inboxes</li></ul><div className="pricing-note"><Coffee size={14} /> Brewing something good. Stay curious.</div></article></div><div className="extension-availability"><div><ChromeIcon size={24} /><span><strong>There’s a little more in your browser.</strong><p>Projects, notes, AI chat, MCP, optional Chrome sync, and reports are already in the developer extension. Connected features need setup.</p></span></div><button onClick={() => setModal('extension')}>Explore the extension <ArrowUpRight size={15} /></button></div></section>

      <section className="faq-section section-wrap" id="faq" aria-labelledby="faq-title"><div className="faq-intro reveal"><div className="eyebrow"><span>?</span> A LITTLE CLARITY</div><h2 id="faq-title">Curious?<br /><span className="serif-word">Of course you are.</span></h2><p>A few things you might be wondering<br />before you settle in.</p><div className="faq-cat" aria-hidden="true"><Cat size={77} variant="faq" /><span>?</span></div></div><div className="faq-list reveal">{faqs.map((faq, i) => <div className={`faq-item ${openFaq === i ? 'open' : ''}`} key={faq.q}><h3><button id={`faq-question-${i}`} onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i} aria-controls={`faq-answer-${i}`}>{faq.q}<span>{openFaq === i ? <X size={17} /> : <Plus size={17} />}</span></button></h3><div className="faq-answer" id={`faq-answer-${i}`} role="region" aria-labelledby={`faq-question-${i}`} hidden={openFaq !== i}><p>{faq.a}</p></div></div>)}</div></section>

      <section className="final-cta section-wrap reveal"><div className="cta-top"><span>A SMALL SIDEKICK. A BIG DIFFERENCE.</span><span>✳</span></div><div className="cta-content"><div className="cta-cat"><Cat size={66} variant="cta" /></div><h2>Your next good day<br />starts with a <span className="serif-word">little focus.</span></h2><p>Close the mental tabs. Open up some possibility.</p><button className="button button-dark" onClick={openInstall}><ChromeIcon size={20} /> Make room for Tabby <ArrowUpRight size={18} /></button><span className="cta-note">Free to try. Easy to love.</span></div><span className="cta-doodle cta-doodle-left" aria-hidden="true">✳</span><svg className="cta-doodle cta-doodle-right" viewBox="0 0 130 120" fill="none" aria-hidden="true"><path d="M8 15c29-8 84-3 89 29S52 72 40 62s-8-20 9-13 36 31 39 57m-15-11 16 13 9-17" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="cta-bottom"><span>YOUR SPACE. YOUR PACE.</span><span>LOTS OF POSSIBILITIES. LESS TABS. ↗</span></div></section>
    </main>

    <footer className="site-footer section-wrap"><div className="footer-main"><div><a href="#" className="brand" aria-label="Tabby home"><BrandLogo /></a><p>A calmer browser.<br />A little more you.</p></div><div className="footer-links"><div><span>THE GOOD STUFF</span><a href="#features">Why Tabby</a><a href="#all-features">All features</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a></div><div><span>A LITTLE MORE</span><a href="#faq">Questions & answers</a><button onClick={() => setModal('privacy')}>Your privacy</button><button onClick={() => setModal('plus')}>What’s next <ArrowUpRight size={12} /></button></div><div className="footer-signoff"><span>MADE FOR REAL LIFE</span><p>Go make something.<br />Or take a little break.<br /><span>We’re rooting for you.</span></p><Heart size={22} /></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Tabby. A little more headspace.</span><span>Made with care, and probably too many tabs. <Cat size={15} /></span><a href="#">Back to top <ArrowUpRight size={13} /></a></div><div className="footer-wordmark" aria-hidden="true">tabby<span>✳</span></div></footer>

    <Modal open={modal === 'workspace'} onClose={() => setModal(null)} className="workspace-modal" label="Try your Tabby workspace"><div className="workspace-modal-heading"><div><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2>A little room to focus.</h2></div><span><Command size={13} /> K to come and go</span></div><Workspace state={workspace} expanded /></Modal>
    <Modal open={modal === 'extension'} onClose={() => setModal(null)} className="installation-modal" label="Install Tabby in Chrome"><InstallationGuide onDemo={() => setModal('workspace')} /></Modal>
    <Modal open={modal === 'plus'} onClose={() => setModal(null)} className="info-modal" label="What’s coming to Tabby"><UpcomingDetails onDemo={() => setModal('workspace')} /></Modal>
    <Modal open={modal === 'privacy'} onClose={() => setModal(null)} className="info-modal privacy-modal" label="Your privacy at Tabby"><div className="info-modal-symbol"><ShieldCheck size={30} /></div><span className="eyebrow">YOUR SPACE MEANS YOUR SPACE</span><h2>A little peace<br /><span className="serif-word">of mind.</span></h2><p>This preview keeps things simple.</p><ul className="privacy-list"><li><Check size={17} /><div><strong>Your tasks stay in this browser.</strong><p>They’re saved in local storage on your device. This site does not upload your task text to a server.</p></div></li><li><Check size={17} /><div><strong>No account. No tracking scripts.</strong><p>There’s no sign-up, payment form, advertising pixel, or analytics service in the preview.</p></div></li><li><Check size={17} /><div><strong>You’re in control.</strong><p>Delete tasks in My tasks, or clear this site’s browser data to remove your saved list. The preview cannot read your browser tabs.</p></div></li><li><ArrowUpRight size={17} /><div><strong>A couple of outside connections.</strong><p>Fonts load from Google Fonts. Example links open third-party websites, which have their own privacy practices.</p></div></li></ul><button className="button button-dark" onClick={() => setModal(null)}>That feels good <Heart size={16} /></button></Modal>
  </>;
}

function ListVisual() { return <span className="list-visual"><Check size={11} /><i /><Check size={11} /><i /><span /><i /></span>; }
